//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminModuleRole
    {
        public int BookingAgentRole_ID { get; set; }
        public int AdminModule_ID { get; set; }
        public bool AdminModuleRole_View { get; set; }
        public bool AdminModuleRole_Add { get; set; }
        public bool AdminModuleRole_Edit { get; set; }
        public bool AdminModuleRole_Delete { get; set; }
    }
}
