//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminPage
    {
        public int Page_ID { get; set; }
        public int Parent_Page_ID { get; set; }
        public int Page_Level { get; set; }
        public string Title { get; set; }
        public string File_Name { get; set; }
    }
}
