//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Air
    {
        public Nullable<int> Ref_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Flght_Fm { get; set; }
        public string Flght_To { get; set; }
        public string Flght_No { get; set; }
        public Nullable<System.DateTime> Dep_Time { get; set; }
        public Nullable<System.DateTime> Arr_Time { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Air_Status { get; set; }
        public string Ask_Fm_Spl { get; set; }
        public int Air_ID { get; set; }
        public Nullable<double> Air_Net { get; set; }
    }
}
