//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirlineScheduleDetail
    {
        public int AirlineScheduleDetailID { get; set; }
        public Nullable<int> AirlineScheduleID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<int> ArrivalCityID { get; set; }
        public Nullable<int> DepartureCityID { get; set; }
        public string SchDesc { get; set; }
        public Nullable<int> CurrType { get; set; }
        public Nullable<double> Air_MarkUp { get; set; }
    }
}
