//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirlineAddOnRate
    {
        public int Airline_ID { get; set; }
        public int Departure_City_ID { get; set; }
        public Nullable<decimal> AirlineAddOnRate_AddOnPrice { get; set; }
        public Nullable<decimal> AirlineAddOnRate_AddOnPriceNet { get; set; }
        public Nullable<double> AirlineAddOnRate_MarkUp { get; set; }
        public Nullable<int> AirlineAddOnRate_CurType { get; set; }
    
        public virtual DepartureCity DepartureCity { get; set; }
    }
}
