//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirlineSurcharge
    {
        public int Airline_Surcharge_ID { get; set; }
        public int Airline_ID { get; set; }
        public Nullable<System.DateTime> AirlineSurcharge_BeginDate { get; set; }
        public Nullable<System.DateTime> AirlineSurcharge_EndDate { get; set; }
        public Nullable<decimal> AirlineSurcharge_Amount { get; set; }
    }
}
