//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiEnvironment
    {
        public int ApiEnvironmentId { get; set; }
        public int ApiUserId { get; set; }
        public int ApiEnvironmentTypeID { get; set; }
        public string ClientID { get; set; }
        public string ClientSecret { get; set; }
        public string RootDomainName { get; set; }
        public Nullable<System.DateTime> LastSecretGenerationDate { get; set; }
        public string LastSecretGenerationIP { get; set; }
        public bool isActive { get; set; }
    }
}
