//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiUserProvider
    {
        public int ApiUserProviderID { get; set; }
        public int ApiUserId { get; set; }
        public byte ProviderId { get; set; }
        public string ApiKey { get; set; }
        public Nullable<int> ProviderCommissionRate { get; set; }
        public bool IsGrossPriceProvider { get; set; }
    
        public virtual ApiUser ApiUser { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
