//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth_Matrix_Member_Type
    {
        public int Auth_Matrix_Member_Type_ID { get; set; }
        public int BookingAgentRole_ID { get; set; }
        public int Auth_Matrix_ID { get; set; }
        public bool Auth_View { get; set; }
        public bool Auth_Edit { get; set; }
    
        public virtual Auth_Matrix Auth_Matrix { get; set; }
        public virtual BookingAgentRole BookingAgentRole { get; set; }
    }
}
