//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth_Element
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auth_Element()
        {
            this.Auth_Matrix = new HashSet<Auth_Matrix>();
        }
    
        public int Auth_Element_ID { get; set; }
        public int Auth_Element_Type_ID { get; set; }
        public string Auth_Element_Name { get; set; }
        public string Description { get; set; }
    
        public virtual Auth_Element_Type Auth_Element_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auth_Matrix> Auth_Matrix { get; set; }
    }
}
