//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoEuropeLocation
    {
        public int Id { get; set; }
        public string AutoEuropeLocationId { get; set; }
        public Nullable<int> Destination_ID { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string CountryCode { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public int AutoEuropeLocationTypeId { get; set; }
        public string IATACode { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string BrandName { get; set; }
        public Nullable<int> MatchType { get; set; }
    }
}
