//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackgroundTaskType
    {
        public int BackgroundTaskTypeID { get; set; }
        public string TypeName { get; set; }
        public string Descripton { get; set; }
        public bool isActive { get; set; }
        public int BackgroundTaskBaseDateID { get; set; }
        public int DelayHours { get; set; }
        public int BackgroundTaskEventID { get; set; }
    }
}
