//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackgroundTask
    {
        public int BackgroundTaskID { get; set; }
        public int BackgroundTaskTypeID { get; set; }
        public string JobManagerID { get; set; }
        public Nullable<int> Ref_ID { get; set; }
        public Nullable<int> Web_User_ID { get; set; }
        public Nullable<System.DateTime> Quote_Start { get; set; }
        public Nullable<System.DateTime> Quote_End { get; set; }
        public Nullable<System.DateTime> Quote_Crt_Date { get; set; }
        public Nullable<System.DateTime> Quote_StatusChangeDate { get; set; }
        public Nullable<int> Quote_Status { get; set; }
        public bool isActive { get; set; }
        public bool isCompleted { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
    }
}
