//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingAgent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingAgent()
        {
            this.BookingAgentDefaultAssistants = new HashSet<BookingAgentDefaultAssistant>();
            this.Contmen = new HashSet<Contman>();
        }
    
        public int Booking_Agent_ID { get; set; }
        public string BookingAgent_FirstName { get; set; }
        public string BookingAgent_LastName { get; set; }
        public string BookingAgent_UserName { get; set; }
        public string BookingAgent_Password { get; set; }
        public Nullable<int> BookingAgentRole_ID { get; set; }
        public string BookingAgent_Email { get; set; }
        public string BookingAgent_PhoneNumber { get; set; }
        public Nullable<int> BookingAgent_PhoneExtension { get; set; }
        public Nullable<int> UserProfile_ID { get; set; }
        public Nullable<bool> BookingAgentCheckout { get; set; }
        public string BookingAgentResponsibleStates { get; set; }
        public bool BookingAgentIsActive { get; set; }
        public bool isVacationModeOn { get; set; }
        public string HubspotMeetingLink { get; set; }
        public Nullable<int> HubspotID { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingAgentDefaultAssistant> BookingAgentDefaultAssistants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contman> Contmen { get; set; }
    }
}
