//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrochureDownload
    {
        public int Brochure_ID { get; set; }
        public int Total_Downloads { get; set; }
        public Nullable<System.DateTime> First_Download { get; set; }
        public Nullable<System.DateTime> Last_Download { get; set; }
    
        public virtual BrochureType BrochureType { get; set; }
    }
}
