//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrochureOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BrochureOrder()
        {
            this.BrochureOrderAmounts = new HashSet<BrochureOrderAmount>();
        }
    
        public int Brochure_ID { get; set; }
        public Nullable<int> Web_User_ID { get; set; }
        public Nullable<short> MediterraneanBrochureAmount { get; set; }
        public Nullable<short> ISPBrochureAmount { get; set; }
        public Nullable<short> GroupManualAmount { get; set; }
        public string TravelAgentCallMePhone { get; set; }
        public string CallTime { get; set; }
        public Nullable<bool> GiveMeQuotation { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<int> Cust_ID { get; set; }
        public Nullable<bool> Sent { get; set; }
        public Nullable<int> SelectRecord { get; set; }
        public Nullable<int> PendingId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrochureOrderAmount> BrochureOrderAmounts { get; set; }
    }
}
