//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrochureOrderAmount
    {
        public int BrochureOrder_ID { get; set; }
        public int BrochureType_ID { get; set; }
        public Nullable<short> BrochureAmount { get; set; }
    
        public virtual BrochureOrder BrochureOrder { get; set; }
        public virtual BrochureType BrochureType { get; set; }
    }
}
