//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrochureType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BrochureType()
        {
            this.BrochureOrderAmounts = new HashSet<BrochureOrderAmount>();
            this.BrochureSubDocuments = new HashSet<BrochureSubDocument>();
        }
    
        public int BrochureType_ID { get; set; }
        public string BrochureTypeName { get; set; }
        public string BrochureShortName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Thumbnail { get; set; }
        public string Document { get; set; }
        public Nullable<int> BrochurePages { get; set; }
        public Nullable<int> BrochureSize { get; set; }
        public Nullable<System.DateTime> PicUploadDate { get; set; }
        public string BrochureObj { get; set; }
        public Nullable<byte> BrochureOrder { get; set; }
        public int MaxOrder { get; set; }
    
        public virtual BrochureDownload BrochureDownload { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrochureOrderAmount> BrochureOrderAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrochureSubDocument> BrochureSubDocuments { get; set; }
    }
}
