//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessRulesDestination
    {
        public int Auto { get; set; }
        public Nullable<int> DestID { get; set; }
        public Nullable<System.DateTime> DestCheckin { get; set; }
        public Nullable<System.DateTime> DestCheckout { get; set; }
        public Nullable<int> DestMarkup { get; set; }
        public Nullable<int> SuplID { get; set; }
        public Nullable<System.DateTime> SuplCheckIn { get; set; }
        public Nullable<System.DateTime> SuplCheckOut { get; set; }
        public Nullable<int> SuplMarkup { get; set; }
        public Nullable<int> SuplMarkupsight { get; set; }
        public Nullable<int> SuplMarkupTrans { get; set; }
        public Nullable<int> FlightMarkUp { get; set; }
        public Nullable<int> CarRentalMarkUp { get; set; }
    }
}
