//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelationRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CancelationRule()
        {
            this.CancelationRuleSubConditions = new HashSet<CancelationRuleSubCondition>();
        }
    
        public int CancelationRuleID { get; set; }
        public int ApiUserId { get; set; }
        public int DaysBeforeServisStartDate { get; set; }
        public string RuleName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Percentage { get; set; }
        public string Description { get; set; }
    
        public virtual ApiUser ApiUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelationRuleSubCondition> CancelationRuleSubConditions { get; set; }
    }
}
