//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRentalApiLog
    {
        public int LogId { get; set; }
        public string ActionType { get; set; }
        public Nullable<int> QuoteId { get; set; }
        public string QueryType { get; set; }
        public string JsonData { get; set; }
        public Nullable<System.DateTime> ExecutionTime { get; set; }
    }
}
