//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatbotPrompt
    {
        public int ID { get; set; }
        public int FlowID { get; set; }
        public string Prompt { get; set; }
        public string Case { get; set; }
        public Nullable<int> CaseID { get; set; }
    
        public virtual ChatbotFlow ChatbotFlow { get; set; }
    }
}
