//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodePromotion
    {
        public int CodePromotion_ID { get; set; }
        public int ApiUserID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string DiscountType { get; set; }
        public double DiscountAmount { get; set; }
        public Nullable<System.DateTime> CheckOutStartDate { get; set; }
        public Nullable<System.DateTime> CheckOutEndDate { get; set; }
        public Nullable<System.DateTime> TripStartDate { get; set; }
        public Nullable<System.DateTime> TripEndDate { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public string SawusPromotion { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string ClientIP { get; set; }
        public decimal minAmount { get; set; }
        public bool isDisposable { get; set; }
        public Nullable<int> earnedRefIdForDisposable { get; set; }
        public Nullable<int> usedRefIdForDisposable { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> ParentCodePromotion_ID { get; set; }
    }
}
