//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commission
    {
        public int Commission_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public string Commission_Code { get; set; }
        public string Commission_Name { get; set; }
        public string Commission_Description { get; set; }
        public string Commission_ConditionType { get; set; }
        public Nullable<System.DateTime> Commission_BookStartDate { get; set; }
        public Nullable<System.DateTime> Commission_BookEndDate { get; set; }
        public Nullable<System.DateTime> Commission_ServiceStartDate { get; set; }
        public Nullable<System.DateTime> Commission_ServiceEndDate { get; set; }
        public string Commission_AdditionType { get; set; }
        public Nullable<double> Commission_Value { get; set; }
    }
}
