//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionPayment
    {
        public int Ref_ID { get; set; }
        public Nullable<int> Cust_ID { get; set; }
        public int Commission_Type { get; set; }
        public Nullable<decimal> Commission_Amount { get; set; }
        public Nullable<bool> Payment_Done { get; set; }
    }
}
