//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyServiceAccess
    {
        public int CompanyServiceAccessID { get; set; }
        public int CompanyID { get; set; }
        public int ServiceTypeID { get; set; }
        public Nullable<decimal> MinStar { get; set; }
        public Nullable<decimal> MaxStar { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
    }
}
