//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyHomePageBanner
    {
        public int CompanyHomePageBannerID { get; set; }
        public int CompanyID { get; set; }
        public string MediaUrl { get; set; }
        public string BannerSlogan { get; set; }
        public bool IsActive { get; set; }
        public int SortOrder { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
