//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyAccountType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyAccountType()
        {
            this.Companies = new HashSet<Company>();
        }
    
        public int CompanyAccountTypeID { get; set; }
        public int ApiUserId { get; set; }
        public string Name { get; set; }
        public int SightseeingCommissionRate { get; set; }
        public int TransferCommissionRate { get; set; }
        public int HotelsCommissionRate { get; set; }
        public int TicketsCommissionRate { get; set; }
        public int TourCommissionRate { get; set; }
        public int CruiseCommissionRate { get; set; }
        public int TransportCommissionRate { get; set; }
        public int CarRentalCommissionRate { get; set; }
        public int FlightCommissionRate { get; set; }
        public int LowCostCommissionRate { get; set; }
        public int AuxiliaryComissionRate { get; set; }
        public int InsuraceCommissionRate { get; set; }
        public int GroupTourCommissionRate { get; set; }
        public int GroupAirCommissionRate { get; set; }
        public int MaximumAddonCommisionRate { get; set; }
    
        public virtual ApiUser ApiUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Companies { get; set; }
    }
}
