//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyPhone
    {
        public int CompanyPhoneID { get; set; }
        public int CompanyID { get; set; }
        public int PhoneID { get; set; }
        public string Extention { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Phone Phone { get; set; }
    }
}
