//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySocialMediaLink
    {
        public int CompanySocialMediaLinkID { get; set; }
        public int CompanyID { get; set; }
        public int SocialMediaTypeID { get; set; }
        public string Url { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual SocialMediaType SocialMediaType { get; set; }
    }
}
