//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyContentAccess
    {
        public int CompanyContentAccessID { get; set; }
        public int CompanyID { get; set; }
        public bool ShowCreateVacation { get; set; }
        public bool ShowLanguageOption { get; set; }
        public int DefaultLanguageID { get; set; }
        public bool ShowCurrencyOption { get; set; }
        public int DefaultCurrencyID { get; set; }
        public bool ShowAIAssistant { get; set; }
    }
}
