//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyPageSetting
    {
        public int CompanyPageSettingsID { get; set; }
        public int CompanyID { get; set; }
        public string TrustPilotWidgetCode { get; set; }
        public string SupportPageUrl { get; set; }
        public string BlogPageUrl { get; set; }
        public string CustomGroupPageUrl { get; set; }
        public bool IsShowHomePageSection1 { get; set; }
        public bool IsShowHomePageSection2 { get; set; }
        public bool IsShowHomePageSection3 { get; set; }
        public bool IsShowHomePageSection4 { get; set; }
        public bool IsShowMailingList { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
