//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.AccreditationCodes = new HashSet<AccreditationCode>();
            this.AuthorityGroups = new HashSet<AuthorityGroup>();
            this.CompanyAddresses = new HashSet<CompanyAddress>();
            this.CompanyHomePageBanners = new HashSet<CompanyHomePageBanner>();
            this.CompanyMembers = new HashSet<CompanyMember>();
            this.CompanyPageSettings = new HashSet<CompanyPageSetting>();
            this.CompanyPhones = new HashSet<CompanyPhone>();
            this.CompanySocialMediaLinks = new HashSet<CompanySocialMediaLink>();
            this.CompanyTags = new HashSet<CompanyTag>();
        }
    
        public int CompanyID { get; set; }
        public Nullable<int> ParentCompanyID { get; set; }
        public int ApiUserId { get; set; }
        public string Name { get; set; }
        public string BrandName { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonTitle { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string LogoUrl { get; set; }
        public string FavicoUrl { get; set; }
        public int CompanyAccountTypeID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> MinimumTotalCommissionRate { get; set; }
        public Nullable<System.DateTime> MinimumTotalCommissionActiveDate { get; set; }
        public string KeytoursDomainName { get; set; }
        public Nullable<int> SawUsID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> TemplateDesignID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccreditationCode> AccreditationCodes { get; set; }
        public virtual ApiUser ApiUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorityGroup> AuthorityGroups { get; set; }
        public virtual CompanyAccountType CompanyAccountType { get; set; }
        public virtual TemplateDesign TemplateDesign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyAddress> CompanyAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyHomePageBanner> CompanyHomePageBanners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyMember> CompanyMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyPageSetting> CompanyPageSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyPhone> CompanyPhones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanySocialMediaLink> CompanySocialMediaLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyTag> CompanyTags { get; set; }
    }
}
