//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contman
    {
        public Nullable<int> Booking_Agent_ID { get; set; }
        public int Contact_ID { get; set; }
        public int Cust_ID { get; set; }
        public Nullable<System.DateTime> Creat_Date { get; set; }
        public Nullable<System.DateTime> Creat_Time { get; set; }
        public string Created_By { get; set; }
        public string Commin_Met { get; set; }
        public Nullable<System.DateTime> Follow_Up { get; set; }
        public string Info { get; set; }
        public Nullable<int> Ref_ID { get; set; }
        public Nullable<int> Result_ID { get; set; }
        public Nullable<int> Request_Id { get; set; }
        public Nullable<int> Contman_Web_User_ID { get; set; }
    
        public virtual BookingAgent BookingAgent { get; set; }
        public virtual Custom Custom { get; set; }
    }
}
