//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryCode
    {
        public string CountryName { get; set; }
        public string CountryCode1 { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public int ID { get; set; }
        public string PhoneCallingCode { get; set; }
    }
}
