//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponSetting
    {
        public int ID { get; set; }
        public int RefID { get; set; }
        public bool isInsuranceIncluded { get; set; }
        public bool isReductionIncluded { get; set; }
        public bool isActive { get; set; }
        public bool isShippingIncluded { get; set; }
        public Nullable<decimal> insuranceAmount { get; set; }
        public Nullable<decimal> reductionAmount { get; set; }
        public Nullable<decimal> shippingAmount { get; set; }
        public bool isDocumentSend { get; set; }
        public Nullable<System.DateTime> documentSendDate { get; set; }
        public Nullable<decimal> couponAmount { get; set; }
        public string voucherNote { get; set; }
        public Nullable<int> additionalCouponPercent { get; set; }
    }
}
