//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmDashboard
    {
        public int CrmID { get; set; }
        public int Web_User_ID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Note { get; set; }
        public int BookingAgent_ID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    }
}
