//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CruiseCabin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CruiseCabin()
        {
            this.CruiseAllotments = new HashSet<CruiseAllotment>();
            this.CruiseScheduleAllotments = new HashSet<CruiseScheduleAllotment>();
            this.SupplierCabins = new HashSet<SupplierCabin>();
        }
    
        public int Cruise_Cabin_ID { get; set; }
        public string CruiseCabin_Name { get; set; }
        public string CruiseCabin_Description { get; set; }
        public string CruiseCabin_Category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CruiseAllotment> CruiseAllotments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CruiseScheduleAllotment> CruiseScheduleAllotments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierCabin> SupplierCabins { get; set; }
    }
}
