//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CruiseTour
    {
        public int CruiseTourID { get; set; }
        public int CruiseID { get; set; }
        public int VoyageID { get; set; }
        public string ShipName { get; set; }
        public string LineName { get; set; }
        public string TourName { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal PriceFrom { get; set; }
        public decimal InsidePriceFrom { get; set; }
        public decimal OutsidePriceFrom { get; set; }
        public decimal BalconyPriceFrom { get; set; }
        public decimal SuitePriceFrom { get; set; }
        public int ProviderCode { get; set; }
        public string Description { get; set; }
    }
}
