//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CruiseSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CruiseSchedule()
        {
            this.CruiseAllotments = new HashSet<CruiseAllotment>();
            this.CruiseScheduleAllotments = new HashSet<CruiseScheduleAllotment>();
        }
    
        public int CruiseSchedule_ID { get; set; }
        public int CruiseLine_ID { get; set; }
        public System.DateTime CruiseSchedule_BeginDate { get; set; }
        public System.DateTime CruiseSchedule_EndDate { get; set; }
        public Nullable<int> CruiseSchedule_AlertValue { get; set; }
        public Nullable<int> CruiseSchedule_DaysBefore { get; set; }
        public Nullable<double> CruiseSchedule_MarkUp { get; set; }
        public Nullable<int> CruiseSchedule_CurType { get; set; }
        public Nullable<int> CruiseSchedule_Increment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CruiseAllotment> CruiseAllotments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CruiseScheduleAllotment> CruiseScheduleAllotments { get; set; }
    }
}
