//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CruiseRegionMatching
    {
        public int ID { get; set; }
        public int CruiseRegionID { get; set; }
        public Nullable<int> TravelTekRegionID { get; set; }
    
        public virtual CruiseRegion CruiseRegion { get; set; }
    }
}
