//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CruiseItinerary
    {
        public int CruiseItineraryID { get; set; }
        public int VoyageID { get; set; }
        public int CruiseID { get; set; }
        public int Day { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> PortId { get; set; }
    }
}
