//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CruiseAllotment
    {
        public int CruiseAllotment_ID { get; set; }
        public int CruiseSchedule_ID { get; set; }
        public int CruiseLine_ID { get; set; }
        public int Cabin_ID { get; set; }
        public Nullable<System.DateTime> CruiseAllotment_Date { get; set; }
        public Nullable<System.DateTime> CruiseAllotment_CancelReminderDate { get; set; }
        public Nullable<int> CruiseAllotment_Total { get; set; }
        public Nullable<int> CruiseAllotment_Booked { get; set; }
        public Nullable<int> CruiseAllotment_Canceled { get; set; }
        public Nullable<int> CruiseAllotment_AlertValue { get; set; }
        public Nullable<decimal> CruiseAllotment_NetPrice { get; set; }
        public Nullable<decimal> CruiseAllotment_GrossPrice { get; set; }
        public Nullable<decimal> CruiseAllotment_AddOnNetPrice { get; set; }
        public Nullable<decimal> CruiseAllotment_AddOnGrossPrice { get; set; }
        public Nullable<double> CruiseAllotment_MarkUp { get; set; }
        public Nullable<int> CruiseAllotment_CurType { get; set; }
        public Nullable<short> SinglePercent { get; set; }
        public Nullable<short> TriplePercent { get; set; }
    
        public virtual CruiseCabin CruiseCabin { get; set; }
        public virtual CruiseSchedule CruiseSchedule { get; set; }
    }
}
