//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CruiseScheduleAllotment
    {
        public int CruiseSchedule_ID { get; set; }
        public int Cabin_ID { get; set; }
        public int Allotted { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public Nullable<decimal> GrossPrice { get; set; }
        public Nullable<decimal> AddOnNetPrice { get; set; }
        public Nullable<decimal> AddOnGrossPrice { get; set; }
        public Nullable<short> SinglePercent { get; set; }
        public Nullable<short> TriplePercent { get; set; }
    
        public virtual CruiseCabin CruiseCabin { get; set; }
        public virtual CruiseSchedule CruiseSchedule { get; set; }
    }
}
