//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int Currency_ID { get; set; }
        public string Currency_Desc { get; set; }
        public string Currency_Detail { get; set; }
        public string Currency_Symbol { get; set; }
    }
}
