//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Custom()
        {
            this.Contmen = new HashSet<Contman>();
            this.CustomerSawUs = new HashSet<CustomerSawU>();
            this.WebUsers = new HashSet<WebUser>();
            this.WebUserInterests = new HashSet<WebUserInterest>();
        }
    
        public Nullable<int> Departure_City_ID { get; set; }
        public int Cust_ID { get; set; }
        public string Company { get; set; }
        public string First { get; set; }
        public string Last { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Ext { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> Created_Da { get; set; }
        public string Clnt_Type { get; set; }
        public Nullable<bool> To_Be_Prin { get; set; }
        public string Title { get; set; }
        public string No_Broch { get; set; }
        public string Notes { get; set; }
        public string E_Mail { get; set; }
        public string Saw_Us { get; set; }
        public string Consursium { get; set; }
        public Nullable<int> Add_Com { get; set; }
        public string Mark_ToBe_ { get; set; }
        public string Arc_No { get; set; }
        public string Last__Chan { get; set; }
        public string IATAN { get; set; }
        public Nullable<System.DateTime> As_Change_ { get; set; }
        public string CLA { get; set; }
        public string Alt_Phone { get; set; }
        public Nullable<double> LandOnlyCommission { get; set; }
        public Nullable<double> AirandLandCommission { get; set; }
        public string WebSite { get; set; }
        public string Province { get; set; }
        public Nullable<double> Tax_ID { get; set; }
        public Nullable<double> Credit_Limit { get; set; }
        public Nullable<bool> Recommended_In_Location { get; set; }
        public Nullable<double> SightseeingCommission { get; set; }
        public Nullable<double> TransferCommission { get; set; }
        public Nullable<double> HotelsCommission { get; set; }
        public Nullable<double> TicketsCommission { get; set; }
        public Nullable<double> OthersCommission { get; set; }
        public Nullable<double> PackageLandCommission { get; set; }
        public Nullable<double> PackageAirCommission { get; set; }
        public Nullable<double> EscortedLandCommission { get; set; }
        public Nullable<double> EscortedAirCommission { get; set; }
        public Nullable<double> TransportCommission { get; set; }
        public Nullable<double> CarRentalCommission { get; set; }
        public Nullable<double> FlightCommission { get; set; }
        public Nullable<double> GroupTourCommission { get; set; }
        public Nullable<double> GroupAirCommission { get; set; }
        public Nullable<double> MinTotalCommission { get; set; }
        public Nullable<System.DateTime> MinTotalCommissionDate { get; set; }
        public Nullable<int> UpdateType { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public string CustomLogo { get; set; }
        public string GenerateURL { get; set; }
        public Nullable<System.DateTime> GenerateURLDate { get; set; }
        public Nullable<System.DateTime> LogoUploadDate { get; set; }
        public Nullable<System.DateTime> CrcDate { get; set; }
        public Nullable<int> old_CustID { get; set; }
        public Nullable<int> UpdatInfo { get; set; }
        public Nullable<int> new_Cust_ID { get; set; }
        public bool DoNotMail { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<int> referralAirCommission { get; set; }
        public Nullable<int> referralLandCommission { get; set; }
        public System.Guid referralGuid { get; set; }
        public Nullable<double> LowCostCommission { get; set; }
        public bool isMigrated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contman> Contmen { get; set; }
        public virtual DepartureCity DepartureCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSawU> CustomerSawUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebUser> WebUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebUserInterest> WebUserInterests { get; set; }
    }
}
