//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPayments_Type
    {
        public int ID { get; set; }
        public int PaymentTypeID { get; set; }
        public string PaymentTypeDesc { get; set; }
        public Nullable<bool> Active { get; set; }
        public bool isToursVisible { get; set; }
    }
}
