//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomDashboardMessage
    {
        public int Message_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Message { get; set; }
        public string Arc_No { get; set; }
    }
}
