//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerPayment()
        {
            this.EscrowPayments = new HashSet<EscrowPayment>();
        }
    
        public int Payment_ID { get; set; }
        public int Ref_ID { get; set; }
        public int PaymentType { get; set; }
        public string VoucherNr { get; set; }
        public string PaymentNotes { get; set; }
        public double PaymentAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int PaymentBy { get; set; }
        public Nullable<int> CreditType { get; set; }
        public Nullable<System.DateTime> CreditExpirationDate { get; set; }
        public string CreditOwner { get; set; }
        public string CreditNumber { get; set; }
        public string CreditSecurityCode { get; set; }
        public string BillingAddressLine1 { get; set; }
        public string BillingAddressLine2 { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZipCode { get; set; }
        public string BillingDayPhone { get; set; }
        public string BillingEveningPhone { get; set; }
        public string BillingName { get; set; }
        public string BillingProvince { get; set; }
        public Nullable<bool> Escrow { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string TransactionId { get; set; }
        public string Country { get; set; }
        public string ExternalName { get; set; }
        public string ExtarnalIP { get; set; }
        public Nullable<System.DateTime> ExtarnalDate { get; set; }
        public string PaymentDocumentType { get; set; }
        public Nullable<int> Tour_ID { get; set; }
        public string ShippingAddressLine1 { get; set; }
        public string ShippingAddressLine2 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingZipCode { get; set; }
        public string ShippingName { get; set; }
        public string ShippingProvince { get; set; }
        public string ShippingCountry { get; set; }
        public string ShippingPhone { get; set; }
        public Nullable<int> Quote_Passenger_ID { get; set; }
        public Nullable<int> CodePromotionID { get; set; }
        public Nullable<short> PaymentAmountType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EscrowPayment> EscrowPayments { get; set; }
    }
}
