//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CXPIssueReport
    {
        public int ID { get; set; }
        public int CxpLogID { get; set; }
        public Nullable<System.Guid> AchGuid { get; set; }
        public Nullable<System.Guid> CartGuid { get; set; }
        public decimal Amount { get; set; }
        public int SupplierID { get; set; }
        public int RefID { get; set; }
        public int PaymentTypeID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
    }
}
