//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CXPLog
    {
        public int ID { get; set; }
        public int SuplID { get; set; }
        public string RequestType { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string RequestBody { get; set; }
        public string ResponseBody { get; set; }
        public Nullable<int> TransactionID { get; set; }
    }
}
