//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartureCityRank
    {
        public int Departure_City_ID { get; set; }
        public int Gateway_City_ID { get; set; }
        public int DepartureCityRank1 { get; set; }
        public int ID { get; set; }
    }
}
