//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationTravelCuriousMatching
    {
        public int ID { get; set; }
        public string TCName { get; set; }
        public string EnglishName { get; set; }
        public string TCID { get; set; }
        public Nullable<int> KeytoursID { get; set; }
        public string LocalDestWithParent { get; set; }
        public string ISO3166Code { get; set; }
    }
}
