//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination_Details
    {
        public int Dest_ID { get; set; }
        public string Country_Name { get; set; }
        public string Geo_Area { get; set; }
        public string Population { get; set; }
        public string Capital_City { get; set; }
        public string People { get; set; }
        public string Lang { get; set; }
        public string Religion { get; set; }
        public string Government { get; set; }
        public string Head_Of_Gov { get; set; }
        public string Visas { get; set; }
        public string Health_Risks { get; set; }
        public string Clothing { get; set; }
        public string Time_Zone { get; set; }
        public string Banking { get; set; }
        public string Currency { get; set; }
        public string Electric_Current { get; set; }
        public string Credit_Cards { get; set; }
        public string Shopping { get; set; }
        public string Measures { get; set; }
        public string Shop_Tax_Free { get; set; }
        public string National_Airport { get; set; }
        public string Major_Attractions { get; set; }
        public string Tipping { get; set; }
        public string AdditionInfo { get; set; }
        public string AllInfo { get; set; }
        public string Embassy { get; set; }
    }
}
