//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationMatching
    {
        public int ID { get; set; }
        public string GooglePlaceID { get; set; }
        public int KeytoursDestID { get; set; }
        public Nullable<int> ViatorDestID { get; set; }
        public string TravelCuriousDestID { get; set; }
        public string IataCode { get; set; }
        public Nullable<int> TravelTekCountryID { get; set; }
    }
}
