//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationPortMatching
    {
        public int DestinationPortMatchingID { get; set; }
        public int DestinationId { get; set; }
        public int TravelTekPortId { get; set; }
        public Nullable<int> SugestedDestinationID { get; set; }
    
        public virtual Destination Destination { get; set; }
        public virtual TravelTekPort TravelTekPort { get; set; }
    }
}
