//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Destination()
        {
            this.CancelationRuleSubConditions = new HashSet<CancelationRuleSubCondition>();
            this.DestinationPortMatchings = new HashSet<DestinationPortMatching>();
            this.MarkupRules = new HashSet<MarkupRule>();
            this.PaymentRuleSubConditions = new HashSet<PaymentRuleSubCondition>();
        }
    
        public int Destination_ID { get; set; }
        public Nullable<int> Parent_Destination_ID { get; set; }
        public string Destination_Name { get; set; }
        public string Destination_Description { get; set; }
        public string Destination_EntryRequirements { get; set; }
        public string Destination_BankHours { get; set; }
        public string Destination_TimeZone { get; set; }
        public string Destination_Picture { get; set; }
        public string Destination_Map { get; set; }
        public string Destination_DetailLink { get; set; }
        public string Destination_TemperatureLink { get; set; }
        public string Destination_PhotoLibraryLink { get; set; }
        public Nullable<int> DestType_ID { get; set; }
        public string Destination_Capital { get; set; }
        public string Destination_LargestCity { get; set; }
        public string Destination_Population { get; set; }
        public Nullable<int> Destination_Level { get; set; }
        public string Destination_Ad { get; set; }
        public Nullable<int> Service_Count { get; set; }
        public Nullable<bool> Destination_IncludesOtherDestinations { get; set; }
        public Nullable<bool> Destination_DisplayOnWebSite { get; set; }
        public Nullable<int> DestinationSortOrder { get; set; }
        public int Destination_HotelCount { get; set; }
        public int Destination_CityPackageCount { get; set; }
        public int Destination_ToursCruiseCount { get; set; }
        public int Destination_SightseeingCount { get; set; }
        public int Destination_TransferCount { get; set; }
        public int Destination_OtherServiceCount { get; set; }
        public Nullable<int> Destination_TicketCount { get; set; }
        public Nullable<int> Destination_SightseeingCountEsc { get; set; }
        public Nullable<System.DateTime> PicUploadDate { get; set; }
        public string Destination_Picture_AltTag { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> Destination_CruiseCount { get; set; }
        public Nullable<byte> MainLandID { get; set; }
        public string MainLandIDNew { get; set; }
        public string MainLandIDNewText { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string SeoKeywords { get; set; }
        public Nullable<int> W2M_DestID { get; set; }
        public bool isSearchable { get; set; }
        public bool isImported { get; set; }
        public string gMapsJSON { get; set; }
        public bool isCoordFromGMaps { get; set; }
        public string Alpha2Code { get; set; }
        public Nullable<int> NumericCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelationRuleSubCondition> CancelationRuleSubConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DestinationPortMatching> DestinationPortMatchings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarkupRule> MarkupRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRuleSubCondition> PaymentRuleSubConditions { get; set; }
    }
}
