//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentOption
    {
        public int ID { get; set; }
        public System.Guid SecureKey { get; set; }
        public int RefID { get; set; }
        public string sendTo { get; set; }
        public bool sendMeToo { get; set; }
        public string mailBody { get; set; }
        public string documentOption1 { get; set; }
        public bool withItemizedCost { get; set; }
        public bool withCommission { get; set; }
        public bool withCommissionPerService { get; set; }
        public bool withDetailItinerary { get; set; }
        public bool withAirItinerary { get; set; }
        public bool withoutPrice { get; set; }
        public string groupBy { get; set; }
        public string attachments { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
