//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doiser
    {
        public int AutoNumber { get; set; }
        public string DoiserNo { get; set; }
        public Nullable<long> ServiceId { get; set; }
        public Nullable<long> RemoteSuplid { get; set; }
        public string RemoteRoomId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string GTAID { get; set; }
        public string HbedInOf { get; set; }
        public string ContactName { get; set; }
        public string SpecialCodes { get; set; }
        public string VoucherURL { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
    }
}
