//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElasticSearchSync
    {
        public int ID { get; set; }
        public int ServiceCategoryID { get; set; }
        public int ServiceID { get; set; }
        public bool isSynced { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
