//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ID { get; set; }
        public string ErrorDetail { get; set; }
        public bool isSolved { get; set; }
        public Nullable<System.DateTime> SolvedDate { get; set; }
        public string Programmer { get; set; }
        public string SolvingDetail { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ErrorType { get; set; }
        public string Message { get; set; }
        public string PageUrl { get; set; }
        public string FormData { get; set; }
        public string Tag { get; set; }
        public string Priority { get; set; }
        public string Comment { get; set; }
    }
}
