//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public int Field_ID { get; set; }
        public string Field_Name { get; set; }
        public string Field_Type { get; set; }
        public string Field_TableName { get; set; }
    }
}
