//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightList
    {
        public int Flight_ID { get; set; }
        public int Ref_ID { get; set; }
        public string FlightNumber { get; set; }
        public System.DateTime FlightDate { get; set; }
        public string FlightFrom { get; set; }
        public string FlightTo { get; set; }
        public string Status { get; set; }
        public string DepartureTime { get; set; }
        public string ArrivalTime { get; set; }
        public Nullable<int> Quote_Passenger_ID { get; set; }
        public Nullable<int> Airline_ID { get; set; }
        public Nullable<double> ArcPriceGross { get; set; }
        public Nullable<double> ArcPriceNet { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public Nullable<bool> Request_Submitted { get; set; }
        public Nullable<int> Service_ID { get; set; }
        public string PNR { get; set; }
        public Nullable<int> Pax { get; set; }
        public Nullable<int> FlightSupl_id { get; set; }
        public Nullable<int> aircomm { get; set; }
        public Nullable<int> LuggageInfoID { get; set; }
        public Nullable<int> TravelClassID { get; set; }
        public int ServiceStatusTypeID { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public string AircraftIata { get; set; }
        public Nullable<int> ConnectingFlightID { get; set; }
        public string FlightDuration { get; set; }
        public string ProviderSegmentId { get; set; }
    }
}
