//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class GarbageBackUpList
    {
        public int BackUpList_ID { get; set; }
        public Nullable<System.DateTime> BackUpList_Date { get; set; }
        public Nullable<bool> Restore { get; set; }
        public string exp { get; set; }
        public Nullable<System.DateTime> BackUp_Date { get; set; }
    }
}
