//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Generate_Code_For_Referer_Friend
    {
        public int Generate_ID { get; set; }
        public System.Guid Code { get; set; }
        public int Web_User_ID { get; set; }
        public bool isClick { get; set; }
        public bool isUsed { get; set; }
        public decimal Amount { get; set; }
        public string targetEmail { get; set; }
        public string targetName { get; set; }
        public string targetLastName { get; set; }
        public Nullable<int> target_Web_User_ID { get; set; }
    }
}
