//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Generate_Code_For_Mini_Website
    {
        public int Generate_ID { get; set; }
        public System.Guid Code { get; set; }
        public int RefID { get; set; }
        public string TopDesc { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool isShared { get; set; }
        public string CreatedFor { get; set; }
        public string EMail { get; set; }
        public bool withoutPrice { get; set; }
        public Nullable<int> MainPassengerID { get; set; }
        public Nullable<int> Quote_Passenger_ID { get; set; }
        public Nullable<int> Web_User_ID { get; set; }
    }
}
