//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomePageBanner
    {
        public int ID { get; set; }
        public int DomainID { get; set; }
        public string Title { get; set; }
        public int ContentTypeID { get; set; }
        public string MediaURL { get; set; }
        public bool isDestinationVisible { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string TitleTargetUrl { get; set; }
        public string BannerContentBox { get; set; }
    }
}
