//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRating
    {
        public int HotelRating_ID { get; set; }
        public string HotelRating_Desc { get; set; }
        public Nullable<byte> ShowDropdown { get; set; }
        public string StarCode { get; set; }
    }
}
