//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class IataAirlineCode
    {
        public int ID { get; set; }
        public string IataCode { get; set; }
        public string IcaoCode { get; set; }
        public string AirlineName { get; set; }
        public string CallsignName { get; set; }
        public string CountryName { get; set; }
    }
}
