//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class IataAircraftCode
    {
        public int ID { get; set; }
        public string iataCode { get; set; }
        public string Manufacturer { get; set; }
        public string AircraftModel { get; set; }
        public string Wake { get; set; }
    }
}
