//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterestTypeService
    {
        public int InterestTypeServiceID { get; set; }
        public Nullable<int> InterestTypeID { get; set; }
        public Nullable<int> Supl_ID { get; set; }
        public Nullable<int> Tour_ID { get; set; }
    
        public virtual InterestType InterestType { get; set; }
    }
}
