//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApply
    {
        public int ID { get; set; }
        public string Position { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string AddInfo { get; set; }
        public System.DateTime Date { get; set; }
        public string Cv { get; set; }
        public int ApiUserId { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
