//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeytoursSubDomain
    {
        public int ID { get; set; }
        public string DomainName { get; set; }
        public string ThemeColor { get; set; }
        public string BackgroundColor { get; set; }
        public string PrimaryColor1 { get; set; }
        public string PrimaryColor2 { get; set; }
        public string SecondaryColor1 { get; set; }
        public string SecondaryColor2 { get; set; }
        public string SecondaryColor3 { get; set; }
    }
}
