//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Landing_List_Org
    {
        public int LandingID { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public string Subject { get; set; }
        public string LandingText { get; set; }
        public string LandingCaption { get; set; }
        public Nullable<System.DateTime> Date_Edit { get; set; }
        public Nullable<System.DateTime> Date_crc { get; set; }
        public Nullable<bool> Active { get; set; }
        public string LandingURL { get; set; }
        public Nullable<bool> StaticPage { get; set; }
    }
}
