//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalImage
    {
        public int LocalImage_ID { get; set; }
        public Nullable<int> Service_Category_ID { get; set; }
        public Nullable<int> Tour_ID { get; set; }
        public Nullable<int> Supl_ID { get; set; }
        public Nullable<int> Destination_ID { get; set; }
        public string LocalImage_FileName { get; set; }
        public bool LocalImage_IsThumb { get; set; }
        public bool LocalImage_IsMap { get; set; }
        public string LocalImage_Tag { get; set; }
        public bool LocalImage_IsProm { get; set; }
    }
}
