//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_ServiceAddOnExpense
    {
        public int Log_Service_Add_On_Expense_ID { get; set; }
        public int Log_Service_ID { get; set; }
        public int Service_Add_On_Expense_ID { get; set; }
        public int Log_Ref_ID { get; set; }
        public int Service_ID { get; set; }
        public string ServiceAddOnExpense_Description { get; set; }
        public Nullable<decimal> ServiceAddOnExpense_Price { get; set; }
        public Nullable<bool> ServiceAddOnExpense_IsRowDeleted { get; set; }
    
        public virtual Log_Quote Log_Quote { get; set; }
    }
}
