//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoyaltyConfiguration
    {
        public int LoyaltyConfigurationID { get; set; }
        public int ApiUserID { get; set; }
        public decimal AirServiceMultiplier { get; set; }
        public decimal LandServiceMultiplier { get; set; }
        public int PointMultiplier { get; set; }
        public int MaximumQuotePricePercentage { get; set; }
        public decimal MinimumUsablePoint { get; set; }
    }
}
