//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoyaltyEarned
    {
        public int LoyaltyEarned_ID { get; set; }
        public int LoyaltyEarned_Ref_ID { get; set; }
        public int MemberID { get; set; }
        public decimal Earned { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public int ApiUserID { get; set; }
    }
}
