//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailTemplate
    {
        public int ID { get; set; }
        public int TypeID { get; set; }
        public string Title { get; set; }
        public string TemplateName { get; set; }
        public string FileURL { get; set; }
        public string PageURL { get; set; }
    }
}
