//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkupProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarkupProfile()
        {
            this.MarkupRules = new HashSet<MarkupRule>();
        }
    
        public int MarkupProfileID { get; set; }
        public int MarkupProfileTypeID { get; set; }
        public Nullable<int> ApiUserId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ApiUser ApiUser { get; set; }
        public virtual MarkupProfileType MarkupProfileType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarkupRule> MarkupRules { get; set; }
    }
}
