//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkupRule
    {
        public int MarkupRuleID { get; set; }
        public int MarkupProfileID { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public Nullable<byte> ServiceTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<byte> ProviderId { get; set; }
        public int Rate { get; set; }
        public int SortNumber { get; set; }
    
        public virtual Destination Destination { get; set; }
        public virtual MarkupProfile MarkupProfile { get; set; }
        public virtual ServiceType ServiceType { get; set; }
    }
}
