//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.CompanyMembers = new HashSet<CompanyMember>();
            this.MemberAddresses = new HashSet<MemberAddress>();
            this.MemberAssistants = new HashSet<MemberAssistant>();
            this.MemberAssistants1 = new HashSet<MemberAssistant>();
            this.MemberAuthorityGroups = new HashSet<MemberAuthorityGroup>();
            this.MemberPhones = new HashSet<MemberPhone>();
            this.SupplierMembers = new HashSet<SupplierMember>();
        }
    
        public int MemberID { get; set; }
        public int ApiUserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> isSendNewsLetter { get; set; }
        public string FacebookID { get; set; }
        public string GoogleID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ApiUser ApiUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyMember> CompanyMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberAddress> MemberAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberAssistant> MemberAssistants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberAssistant> MemberAssistants1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberAuthorityGroup> MemberAuthorityGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberPhone> MemberPhones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierMember> SupplierMembers { get; set; }
    }
}
