//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAuthorityGroup
    {
        public int MemberAuthorityGroupID { get; set; }
        public int MemberID { get; set; }
        public int AuthorityGroupID { get; set; }
    
        public virtual AuthorityGroup AuthorityGroup { get; set; }
        public virtual Member Member { get; set; }
    }
}
