//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAddress
    {
        public int MemberAddressID { get; set; }
        public int MemberID { get; set; }
        public int AddressID { get; set; }
        public int AddressTypeID { get; set; }
        public bool IsMain { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual AddressType AddressType { get; set; }
        public virtual Member Member { get; set; }
    }
}
