//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationMenuItem
    {
        public int OperationMenuItem_ID { get; set; }
        public int ParentID { get; set; }
        public string ItemName { get; set; }
        public string Url { get; set; }
        public string Image { get; set; }
        public int SortID { get; set; }
    }
}
