//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParsecHotelPhoto
    {
        public int ID { get; set; }
        public int ParsecHotelID { get; set; }
        public string ParsecHotelPic { get; set; }
        public Nullable<int> ProviderCode { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<bool> isFailed { get; set; }
    }
}
