//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParsecDestination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParsecDestination()
        {
            this.ProviderHotelFacilityRelations = new HashSet<ProviderHotelFacilityRelation>();
            this.ProviderHotelPointOfInterests = new HashSet<ProviderHotelPointOfInterest>();
        }
    
        public string CityName { get; set; }
        public string AreaName { get; set; }
        public string StateName { get; set; }
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> ParceDestsId { get; set; }
        public int ParcesHotelId { get; set; }
        public string HotelName { get; set; }
        public string Adress { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> KeytourId { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public Nullable<int> KeyTourHotelID { get; set; }
        public Nullable<int> ProviderCode { get; set; }
        public string ProviderName { get; set; }
        public string ProviderPhone { get; set; }
        public Nullable<int> LocalSupplier { get; set; }
        public Nullable<int> OptNumber { get; set; }
        public Nullable<int> autoNumber { get; set; }
        public Nullable<bool> referance { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string ThumName { get; set; }
        public Nullable<bool> Control { get; set; }
        public Nullable<bool> ManuelCnt { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string GTAHotelKey { get; set; }
        public string GTADestKey { get; set; }
        public string ProviderFax { get; set; }
        public string ProviderEmail { get; set; }
        public Nullable<int> MatchingID { get; set; }
        public Nullable<int> UpdateFlag { get; set; }
        public string TelFormatNew { get; set; }
        public string FaxFormatNew { get; set; }
        public string KeytoursKey { get; set; }
        public string StarHotel { get; set; }
        public Nullable<decimal> HotelStar { get; set; }
        public string Category { get; set; }
        public string serviceType { get; set; }
        public Nullable<bool> updatecn { get; set; }
        public string LocationNew { get; set; }
        public Nullable<bool> CategoryUpdate { get; set; }
        public string W2M_CODE { get; set; }
        public string TS_CODE { get; set; }
        public string MIKI_CODE { get; set; }
        public string TTHOT_CODE { get; set; }
        public string ICA_CODE { get; set; }
        public string TFS_CODE { get; set; }
        public string TCOP_CODE { get; set; }
        public Nullable<bool> isUpdated { get; set; }
        public Nullable<long> VervotechId { get; set; }
        public string GetARoomId { get; set; }
        public string CosmobedsId { get; set; }
        public string Website { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> ChainId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<decimal> KeytoursRating { get; set; }
        public Nullable<bool> isMatchedByLocation { get; set; }
        public string GooglePlaceID { get; set; }
        public Nullable<System.DateTime> LastReviewUpdateDate { get; set; }
        public Nullable<decimal> ReviewRating { get; set; }
        public Nullable<int> TotalReviewCount { get; set; }
        public string AmadeusAVHId { get; set; }
        public string AmadeusGDSId { get; set; }
        public string RestelId { get; set; }
        public Nullable<bool> isRiskyMatch { get; set; }
        public string DestinationItaliaId { get; set; }
        public Nullable<int> KeytourIdOld { get; set; }
        public Nullable<bool> isNewHotel { get; set; }
        public string PriceTravelId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderHotelFacilityRelation> ProviderHotelFacilityRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderHotelPointOfInterest> ProviderHotelPointOfInterests { get; set; }
    }
}
