//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentRule()
        {
            this.PaymentRuleSubConditions = new HashSet<PaymentRuleSubCondition>();
        }
    
        public int PaymentRuleID { get; set; }
        public int PaymentRuleProfileID { get; set; }
        public string RuleName { get; set; }
        public int PaymentRuleBaseDateID { get; set; }
        public int BaseDateModifier { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Percentage { get; set; }
        public string Description { get; set; }
    
        public virtual PaymentRuleBaseDate PaymentRuleBaseDate { get; set; }
        public virtual PaymentRuleProfile PaymentRuleProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRuleSubCondition> PaymentRuleSubConditions { get; set; }
    }
}
