//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRuleSubCondition
    {
        public int PaymentRuleSubConditionID { get; set; }
        public int PaymentRuleID { get; set; }
        public Nullable<byte> ServiceTypeId { get; set; }
        public Nullable<int> Supl_ID { get; set; }
        public Nullable<int> Destination_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Percentage { get; set; }
        public string Description { get; set; }
        public int SortNumber { get; set; }
    
        public virtual Destination Destination { get; set; }
        public virtual PaymentRule PaymentRule { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
