//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRuleProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentRuleProfile()
        {
            this.PaymentRules = new HashSet<PaymentRule>();
        }
    
        public int PaymentRuleProfileID { get; set; }
        public int ApiUserId { get; set; }
        public string Name { get; set; }
        public bool isDefault { get; set; }
    
        public virtual ApiUser ApiUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRule> PaymentRules { get; set; }
    }
}
