//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingNote
    {
        public Nullable<int> PendingId { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string Notes { get; set; }
        public Nullable<int> admin_id { get; set; }
        public string Admin_Name { get; set; }
        public string CallNote { get; set; }
        public int Aotu_id { get; set; }
        public Nullable<int> Ref_ID { get; set; }
        public Nullable<int> CustID { get; set; }
        public Nullable<int> WebuserID { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
    }
}
