//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pending
    {
        public int Auto_id { get; set; }
        public string Gateway { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public Nullable<short> RoomPax { get; set; }
        public string Category { get; set; }
        public string Consorsium { get; set; }
        public string itinery { get; set; }
        public Nullable<int> Cust_id { get; set; }
        public Nullable<int> WebUser_id { get; set; }
        public string Meal { get; set; }
        public Nullable<int> Admin_Id { get; set; }
        public string Admin_Name { get; set; }
        public Nullable<bool> PenRowDelete { get; set; }
        public Nullable<int> SawusId { get; set; }
        public Nullable<int> Ref_id { get; set; }
        public string Source { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> TourID { get; set; }
        public string Phone { get; set; }
        public string Tags { get; set; }
        public Nullable<System.DateTime> Assign_Date { get; set; }
        public Nullable<int> AssingBy_Agent { get; set; }
        public Nullable<int> pendingflag { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductDestID { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public string PromotionCodePending { get; set; }
        public string ContactName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string Phone1 { get; set; }
        public string Province { get; set; }
        public string Company { get; set; }
        public string HotelCategory { get; set; }
        public string DepartureDate { get; set; }
        public string Destination { get; set; }
        public Nullable<byte> GroupSize { get; set; }
        public string interestType { get; set; }
        public string RequestLink { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string HubSpotDeallD { get; set; }
    }
}
