//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingPass
    {
        public Nullable<int> TravPendingId { get; set; }
        public int TravAutoId { get; set; }
        public string TravellerGender { get; set; }
        public string TravellerName { get; set; }
        public string TravellerSurname { get; set; }
        public Nullable<int> TravvellerAge { get; set; }
    }
}
