//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreferredProduct
    {
        public int PreferredID { get; set; }
        public int ApiUserID { get; set; }
        public int CompanyID { get; set; }
        public string TourID { get; set; }
        public string SupplierID { get; set; }
        public Nullable<int> ParsecID { get; set; }
        public string ViatorCode { get; set; }
    }
}
