//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateTourPricing
    {
        public int TourSchedule_ID { get; set; }
        public int PrivateTourPricing_NumberOfPassengers { get; set; }
        public Nullable<decimal> PrivateTourPricing_PricePerPassenger { get; set; }
        public Nullable<decimal> PrivateTourPricing_PricePerPassengerNet { get; set; }
        public Nullable<double> PrivateTourPricing_MarkUp { get; set; }
        public Nullable<int> PrivateTourPricing_CurType { get; set; }
    
        public virtual TourSchedule TourSchedule { get; set; }
    }
}
