//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateTourPricingByVehicle
    {
        public int ID { get; set; }
        public int TourSchedule_ID { get; set; }
        public int SeatFrom { get; set; }
        public int SeatTo { get; set; }
        public decimal Price { get; set; }
    }
}
