//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateTourPrice
    {
        public int Tour_ID { get; set; }
        public int PrivateTourPrice_NumberOfPassengers { get; set; }
        public Nullable<decimal> PrivateTourPrice_Price { get; set; }
        public Nullable<decimal> PrivateTourPrice_PriceNet { get; set; }
        public Nullable<double> PrivateTourPrice_MarkUp { get; set; }
        public Nullable<int> PrivateTourPrice_CurType { get; set; }
        public Nullable<int> Tour_Schedule_ID { get; set; }
    }
}
