//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promotion()
        {
            this.PromotionConditions = new HashSet<PromotionCondition>();
        }
    
        public int Promotion_ID { get; set; }
        public int ApiUserID { get; set; }
        public string Promotion_Code { get; set; }
        public string Promotion_Name { get; set; }
        public string Promotion_Description { get; set; }
        public string Promotion_Type { get; set; }
        public Nullable<System.DateTime> Promotion_BeginDate { get; set; }
        public Nullable<System.DateTime> Promotion_EndDate { get; set; }
        public Nullable<System.DateTime> Promotion_EffectiveBeginDate { get; set; }
        public Nullable<System.DateTime> Promotion_EffectiveEndDate { get; set; }
        public string Promotion_DiscountType { get; set; }
        public Nullable<double> Promotion_DefaultDiscountValue { get; set; }
        public Nullable<bool> Promotion_DisplayOnMainServicePage { get; set; }
        public Nullable<bool> Promotion_DisplayOnMainDestPage { get; set; }
        public Nullable<bool> Promotion_DisplayOnSpecialPage { get; set; }
        public Nullable<bool> Promotion_DisplayOnHomePage { get; set; }
        public string Promotion_Picture { get; set; }
        public Nullable<int> Promotion_Rank { get; set; }
        public Nullable<bool> Promotion_DisplayOnPopupPage { get; set; }
        public Nullable<bool> Promotion_Apply { get; set; }
        public string Promotion_PictureMain { get; set; }
        public Nullable<int> Promotion_ParDestID { get; set; }
        public string Promotion_Slogan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionCondition> PromotionConditions { get; set; }
    }
}
