//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionCondition
    {
        public int Promotion_ID { get; set; }
        public int Promotion_Condition_ID { get; set; }
        public int Field_ID { get; set; }
        public string PromotionCondition_Operator { get; set; }
        public string PromotionCondition_Value { get; set; }
    
        public virtual Promotion Promotion { get; set; }
    }
}
