//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionDiscountsPerPassenger
    {
        public int ID { get; set; }
        public int PromotionID { get; set; }
        public int TypeID { get; set; }
        public bool HasAir { get; set; }
        public int PassengerCount { get; set; }
        public decimal DiscountValue { get; set; }
    }
}
