//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderHotelFacilityGroupsRelation
    {
        public int ID { get; set; }
        public int FacilityGroupID { get; set; }
        public int FacilityID { get; set; }
    
        public virtual ProviderHotelFacility ProviderHotelFacility { get; set; }
        public virtual ProviderHotelFacilityGroup ProviderHotelFacilityGroup { get; set; }
    }
}
