//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderHotelFacility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProviderHotelFacility()
        {
            this.ProviderHotelFacilityRelations = new HashSet<ProviderHotelFacilityRelation>();
            this.ProviderHotelFacilityGroupsRelations = new HashSet<ProviderHotelFacilityGroupsRelation>();
        }
    
        public int Id { get; set; }
        public string FacilityName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderHotelFacilityRelation> ProviderHotelFacilityRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderHotelFacilityGroupsRelation> ProviderHotelFacilityGroupsRelations { get; set; }
    }
}
