//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderHotelFacilityRelation
    {
        public int Id { get; set; }
        public int ParsecHotelId { get; set; }
        public int FacilityId { get; set; }
    
        public virtual ParsecDestination ParsecDestination { get; set; }
        public virtual ProviderHotelFacility ProviderHotelFacility { get; set; }
    }
}
