//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp_ExcInc
    {
        public int Exclnc_ID { get; set; }
        public string ExcInc_Description { get; set; }
        public string ExcInc_Type { get; set; }
    }
}
