//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotePassengerLoyaltyProgram
    {
        public int ID { get; set; }
        public int QuotePassengerID { get; set; }
        public int LoyaltyProgramID { get; set; }
        public string ProgramNumber { get; set; }
    }
}
