//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp_Tours
    {
        public int Tour_ID { get; set; }
        public string Tour_Code { get; set; }
        public string Tour_Name { get; set; }
        public Nullable<int> Destination_ID { get; set; }
        public Nullable<System.DateTime> Crc_Date { get; set; }
        public string Starts { get; set; }
        public string Ends { get; set; }
        public string Operated_By { get; set; }
        public string Min_Pax { get; set; }
        public string Catagory_ID { get; set; }
        public string Notes { get; set; }
        public string Advise_Booking { get; set; }
        public string Itinerary { get; set; }
        public string Airline { get; set; }
        public string Duration { get; set; }
        public string Distance { get; set; }
        public string Price { get; set; }
    }
}
