//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp_Proposal_Include
    {
        public int INC_ID { get; set; }
        public Nullable<int> Proposal_ID { get; set; }
        public Nullable<double> Ref_ID { get; set; }
        public string Service_Notes { get; set; }
        public Nullable<int> Exclnc_ID { get; set; }
    }
}
