//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp_PreDefined
    {
        public int Quotegrp_PreDefinedID { get; set; }
        public int Quotegrp_PreDefinedReferanceDateID { get; set; }
        public Nullable<decimal> DepositAmount1 { get; set; }
        public Nullable<int> DepositDueDate1 { get; set; }
        public Nullable<decimal> DepositAmount2 { get; set; }
        public Nullable<int> DepositDueDate2 { get; set; }
        public Nullable<int> FinalDueDate { get; set; }
        public Nullable<int> NameListDate { get; set; }
        public int Quotegrp_PreDefinedDepartmentID { get; set; }
        public Nullable<decimal> AirMarkUp { get; set; }
        public Nullable<decimal> LandMarkUp { get; set; }
    }
}
