//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote_Auto_Assign
    {
        public int ID { get; set; }
        public int ApiUserId { get; set; }
        public int Booking_Agent_ID { get; set; }
        public System.DateTime Last_Assign_Date { get; set; }
    }
}
