//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote_Old
    {
        public int Ref_ID { get; set; }
        public string TmpShipid { get; set; }
        public string Shipping_ID { get; set; }
        public Nullable<int> Cust_ID { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public string Room { get; set; }
        public Nullable<int> Pax { get; set; }
        public Nullable<System.DateTime> Crt_Date { get; set; }
        public string Booking_Agent_ID { get; set; }
        public string Destn { get; set; }
        public string Contact { get; set; }
        public string Tour_Type { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Mdf_Date { get; set; }
        public Nullable<int> Mdf_By_Booking_Agent_ID { get; set; }
        public Nullable<System.DateTime> Crt_Time { get; set; }
        public Nullable<System.DateTime> Mdf_Time { get; set; }
        public string Tour_Name { get; set; }
        public string Tour_Code { get; set; }
        public Nullable<int> Mark { get; set; }
        public string Early_Mail { get; set; }
        public string Referred_By { get; set; }
        public Nullable<decimal> Arc_Paym { get; set; }
        public Nullable<bool> Mrk_Escrw { get; set; }
        public Nullable<int> To_Supl { get; set; }
        public Nullable<System.DateTime> Rec_Chndate { get; set; }
        public string Quote_Name { get; set; }
        public Nullable<int> Web_User_ID { get; set; }
        public Nullable<bool> Quote_CreateOnWeb { get; set; }
        public bool Quote_IsRowDeleted { get; set; }
        public string Quote_DocumentStatus { get; set; }
        public Nullable<double> Quote_TripCost { get; set; }
        public Nullable<double> Quote_TripDeposit { get; set; }
        public Nullable<int> BookingAgent_ID { get; set; }
        public Nullable<System.DateTime> Quote_CheckOutDate { get; set; }
        public Nullable<System.DateTime> Quote_DepositDueDate { get; set; }
        public Nullable<System.DateTime> Quote_FullDueDate { get; set; }
        public double Quote_TripReduction { get; set; }
        public string Quote_PromotionCode { get; set; }
        public string Quote_InternalNotes { get; set; }
        public string Quote_SupplierMemo { get; set; }
        public string User_Notes { get; set; }
        public Nullable<byte> Deposit_Updated { get; set; }
        public Nullable<byte> MailSent { get; set; }
        public Nullable<int> TotalItems { get; set; }
        public Nullable<decimal> TripCost { get; set; }
        public Nullable<double> InsuranceAmount { get; set; }
        public Nullable<double> CommissionTotal { get; set; }
        public Nullable<double> CommissionService { get; set; }
        public Nullable<double> CommissionInsurance { get; set; }
        public Nullable<bool> InsuranceConfirm { get; set; }
        public Nullable<bool> InsurancePaid { get; set; }
        public Nullable<System.DateTime> InsConfirmDate { get; set; }
        public Nullable<bool> CommtoPayment { get; set; }
        public Nullable<System.DateTime> StatusChangeDate { get; set; }
        public Nullable<System.DateTime> CommtoPaymentDate { get; set; }
        public Nullable<int> OldStatus { get; set; }
        public Nullable<int> OldBookingAgent { get; set; }
        public Nullable<System.DateTime> cancellationsdate { get; set; }
        public Nullable<double> cancellationsamount { get; set; }
        public Nullable<double> revisionAmount { get; set; }
        public string StatusOnline { get; set; }
        public string DoisserNo { get; set; }
        public Nullable<double> TotalAirPrice { get; set; }
        public Nullable<int> CommPayDone { get; set; }
        public string cancellationamountDesc { get; set; }
        public string revisionAmountDesc { get; set; }
        public string QuoteType { get; set; }
        public Nullable<int> StageID { get; set; }
        public Nullable<int> LostReasonID { get; set; }
        public Nullable<int> PriceDiffControl { get; set; }
        public Nullable<int> new_Cust_ID { get; set; }
        public Nullable<int> Old_Cust_ID { get; set; }
        public Nullable<int> UpdateInfo { get; set; }
        public Nullable<int> G_StartDestID { get; set; }
        public Nullable<int> G_EndDestID { get; set; }
        public string Group_Name { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<System.DateTime> Quote_EmailSend { get; set; }
        public Nullable<bool> MailingAdressUse_WebUser { get; set; }
        public Nullable<double> InsuranceAmount_Old { get; set; }
        public Nullable<System.DateTime> InsUpdateDate { get; set; }
        public Nullable<System.DateTime> InsuranceDate_Old { get; set; }
        public Nullable<int> IframeReference { get; set; }
        public string AirItinerary { get; set; }
        public bool CreatedByWebUser { get; set; }
        public bool PointApplied { get; set; }
        public bool isSentPostTrip { get; set; }
        public bool isSentPaymentFull { get; set; }
        public bool isSentPaymentDeposit { get; set; }
        public bool isSentTravelDocument { get; set; }
        public Nullable<decimal> AddOnCommission { get; set; }
        public Nullable<bool> isShowNetPrice { get; set; }
        public string RoomSelectPatternJson { get; set; }
        public Nullable<decimal> PromCommissionAdd { get; set; }
        public Nullable<bool> isShowPriceOnTripDetail { get; set; }
        public Nullable<bool> isShowCommisionOnTripDetail { get; set; }
        public bool isReferral { get; set; }
        public Nullable<int> referralCustID { get; set; }
        public Nullable<System.Guid> CXPGroupGuid { get; set; }
        public Nullable<System.DateTime> CheckOutStartDate { get; set; }
        public bool isBuyOnMiniWebSiteDisabled { get; set; }
        public Nullable<int> ConsumerID { get; set; }
    }
}
