//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp_Service_Detail
    {
        public int Service_Detail_ID { get; set; }
        public int Service_ID { get; set; }
        public string Room_Type { get; set; }
        public Nullable<double> Room_Price { get; set; }
        public Nullable<int> Room_Nr { get; set; }
        public Nullable<double> Total_Price { get; set; }
        public Nullable<int> Pax { get; set; }
        public Nullable<int> Proposal_ID { get; set; }
        public Nullable<int> Ref_ID { get; set; }
        public string Notes { get; set; }
        public byte[] TmpStamp { get; set; }
    }
}
