//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteCommissionDetail
    {
        public int QuoteCommissionDetail_ID { get; set; }
        public int Ref_ID { get; set; }
        public decimal Amount { get; set; }
        public int QuoteCommissionDetailTypeID { get; set; }
        public string Code { get; set; }
    }
}
