//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp_Proposal_Air
    {
        public int AIRGRP_ID { get; set; }
        public Nullable<int> Proposal_ID { get; set; }
        public Nullable<double> Ref_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Flight_FM { get; set; }
        public string Flight_TO { get; set; }
        public string Flight_NO { get; set; }
        public string Dep_Time { get; set; }
        public string Arr_Time { get; set; }
        public Nullable<double> Price { get; set; }
        public string Air_Status { get; set; }
        public string Air_Pnr { get; set; }
    }
}
