//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp_Proposal
    {
        public int Proposal_ID { get; set; }
        public Nullable<System.DateTime> Crc_Date { get; set; }
        public Nullable<System.DateTime> Modf_Date { get; set; }
        public Nullable<int> Modf_By { get; set; }
        public Nullable<double> REF_ID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> P_Increment { get; set; }
        public Nullable<int> P_GroupSize { get; set; }
        public Nullable<int> P_GroupMin { get; set; }
        public Nullable<double> Air_Mark { get; set; }
        public Nullable<double> Tour_Mark { get; set; }
        public string Price_Sing { get; set; }
        public Nullable<double> Other_Price1 { get; set; }
        public Nullable<double> Other_Price2 { get; set; }
        public Nullable<double> Other_Price3 { get; set; }
        public Nullable<double> Other_Price4 { get; set; }
        public Nullable<double> Other_Price5 { get; set; }
        public Nullable<double> Other_Price6 { get; set; }
        public Nullable<double> Other_PriceSgl { get; set; }
        public Nullable<double> Other_Price7 { get; set; }
        public Nullable<double> Quote_Price1 { get; set; }
        public Nullable<double> Quote_Price2 { get; set; }
        public Nullable<double> Quote_Price3 { get; set; }
        public Nullable<double> Quote_Price4 { get; set; }
        public Nullable<double> Quote_Price5 { get; set; }
        public Nullable<double> Quote_Price6 { get; set; }
        public Nullable<double> Quote_Price7 { get; set; }
        public Nullable<System.DateTime> Quote_Set { get; set; }
        public Nullable<double> Quote_SGL { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Quote_PriceLabel1 { get; set; }
        public string Quote_PriceLabel2 { get; set; }
        public string Quote_PriceLabel3 { get; set; }
        public string Quote_PriceLabel4 { get; set; }
        public string Quote_PriceLabel5 { get; set; }
        public string Quote_PriceLabel6 { get; set; }
        public string Quote_PriceLabel7 { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> StartDest_ID { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> EndDest_ID { get; set; }
        public Nullable<System.DateTime> Deposit1Date { get; set; }
        public Nullable<double> Deposit1 { get; set; }
        public Nullable<System.DateTime> Deposit2Date { get; set; }
        public Nullable<double> Deposit2 { get; set; }
        public string Validity { get; set; }
        public Nullable<double> FinalPayment { get; set; }
        public Nullable<System.DateTime> FinalPaymentDate { get; set; }
        public string ExchangeRate { get; set; }
        public string Room { get; set; }
        public Nullable<double> AirportTax { get; set; }
        public Nullable<double> HarborTax { get; set; }
        public string AirAddOn { get; set; }
        public Nullable<System.DateTime> NameListDate { get; set; }
        public Nullable<System.DateTime> ExchangeRateDate { get; set; }
        public Nullable<int> ProposalComm { get; set; }
        public string P_Group_Name { get; set; }
        public Nullable<System.DateTime> ValidityDate { get; set; }
        public Nullable<double> AirDeposit { get; set; }
        public Nullable<System.DateTime> AirDepositDate { get; set; }
        public Nullable<double> FreeCost1 { get; set; }
        public Nullable<double> FreeCost2 { get; set; }
        public Nullable<double> FreeCost3 { get; set; }
        public Nullable<double> FreeCost4 { get; set; }
        public Nullable<double> FreeCost5 { get; set; }
        public Nullable<double> FreeCost6 { get; set; }
        public Nullable<double> FreeCost7 { get; set; }
        public Nullable<double> GroupTourCommission { get; set; }
        public Nullable<double> GroupAirCommission { get; set; }
        public Nullable<double> CommissionAmount1 { get; set; }
        public Nullable<double> CommissionAmount2 { get; set; }
        public Nullable<double> CommissionAmount3 { get; set; }
        public Nullable<double> CommissionAmount4 { get; set; }
        public Nullable<double> CommissionAmount5 { get; set; }
        public Nullable<double> CommissionAmount6 { get; set; }
        public Nullable<double> CommissionAmount7 { get; set; }
        public Nullable<double> AirCommissionAmount1 { get; set; }
        public Nullable<double> AirCommissionAmount2 { get; set; }
        public Nullable<double> AirCommissionAmount3 { get; set; }
        public Nullable<double> AirCommissionAmount4 { get; set; }
        public Nullable<double> AirCommissionAmount5 { get; set; }
        public Nullable<double> AirCommissionAmount6 { get; set; }
    }
}
