//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp_Referals
    {
        public int ID { get; set; }
        public Nullable<double> REFERAL_ID { get; set; }
        public string NAME { get; set; }
        public string INITIALS { get; set; }
        public string LOCATION { get; set; }
        public string TYPE { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
