//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp_Proposal_GenExp
    {
        public int GenExp_ID { get; set; }
        public Nullable<int> Proposal_ID { get; set; }
        public Nullable<double> Ref_ID { get; set; }
        public Nullable<int> Gen_Dest_ID { get; set; }
        public Nullable<System.DateTime> Gen_Date { get; set; }
        public Nullable<double> Gen_DAY { get; set; }
        public string Gen_Desc { get; set; }
        public Nullable<double> Gen_Price { get; set; }
        public Nullable<int> Gen_Qnt { get; set; }
        public Nullable<double> Gen_Total { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
