//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp_Proposal_N
    {
        public int ID { get; set; }
        public Nullable<double> AIRFARE_MA { get; set; }
        public Nullable<double> TOUR_MARK_ { get; set; }
        public string PRICE_SING { get; set; }
        public Nullable<double> REF_ID { get; set; }
        public Nullable<double> OTH_PRICE1 { get; set; }
        public Nullable<double> OTH_PRICE2 { get; set; }
        public Nullable<double> OTH_PRICE3 { get; set; }
        public Nullable<double> OTH_PRICE4 { get; set; }
        public Nullable<double> OTH_PRICE5 { get; set; }
        public Nullable<double> OTH_PRICE6 { get; set; }
        public Nullable<double> OTH_SGL_SP { get; set; }
        public Nullable<double> OTH_PRICE7 { get; set; }
        public string PROPOSL_ID { get; set; }
        public Nullable<double> OUOTE_1 { get; set; }
        public Nullable<double> OUOTE_2 { get; set; }
        public Nullable<double> QUOTE_3 { get; set; }
        public Nullable<double> QUOTE_4 { get; set; }
        public Nullable<double> QUOTE_6 { get; set; }
        public Nullable<double> QUOTE_5 { get; set; }
        public Nullable<double> QUOTE_SGL_ { get; set; }
        public string QUOTE__SET { get; set; }
        public string REVISION { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
