//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp_Names_Rooms_Assign
    {
        public int RoomAssignID { get; set; }
        public Nullable<int> Ref_ID { get; set; }
        public Nullable<int> Service_ID { get; set; }
        public string RoomType { get; set; }
        public Nullable<int> RomNumber { get; set; }
        public string RoomDescp { get; set; }
        public string Traveller1 { get; set; }
        public string Traveller2 { get; set; }
        public string Traveller3 { get; set; }
        public string Description { get; set; }
    }
}
