//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotePassenger_old
    {
        public int Quote_Passenger_ID { get; set; }
        public Nullable<int> Parent_Quote_Passenger_ID { get; set; }
        public int Ref_ID { get; set; }
        public string Passenger_FirstName { get; set; }
        public string Passenger_LastName { get; set; }
        public string Passenger_Gender { get; set; }
        public Nullable<int> Passenger_Age { get; set; }
        public string Passenger_SpecialRequest { get; set; }
        public Nullable<decimal> Passenger_TravelInsurance { get; set; }
        public Nullable<double> Passenger_Reduction { get; set; }
        public bool QuotePassenger_IsRowDeleted { get; set; }
        public string RoomRequirement { get; set; }
        public Nullable<bool> Smoking { get; set; }
        public string Phone { get; set; }
        public string EmergencyContact { get; set; }
        public string VegeterianHealtRequirement { get; set; }
        public Nullable<int> Web_User_ID { get; set; }
        public Nullable<System.DateTime> Passenger_InsuranceDate { get; set; }
        public bool isInsuranceConfirmed { get; set; }
        public string EmergencyContactNo { get; set; }
        public string Passenger_PassPortNo { get; set; }
        public string Passenger_PassPortIssueDate { get; set; }
        public string Passenger_PassPortIExpirationDate { get; set; }
        public Nullable<System.DateTime> Passenger_BirthDate { get; set; }
        public string Passenger_Citizenship { get; set; }
        public string Passenger_GenderFM { get; set; }
        public string Passenger_Email { get; set; }
        public string Passenger_Address1 { get; set; }
        public string Passenger_Address2 { get; set; }
        public string Passenger_City { get; set; }
        public string Passenger_State { get; set; }
        public string Passenger_ZipCode { get; set; }
        public string Passenger_Country { get; set; }
        public string Passenger_Province { get; set; }
        public Nullable<short> GTAPass_ID { get; set; }
        public Nullable<short> HBedPass_ID { get; set; }
        public Nullable<int> RoomAssignID { get; set; }
        public Nullable<decimal> Passenger_QuoteReduction { get; set; }
        public Nullable<double> Passenger_QuotePerperson { get; set; }
        public Nullable<double> Passenger_PerPerson_Cancellationfee { get; set; }
        public Nullable<double> Passenger_PerPerson_Revisionfee { get; set; }
        public Nullable<System.DateTime> Passenger_InsuranceDate_Old { get; set; }
        public Nullable<double> Passenger_TravelInsurance_old { get; set; }
        public Nullable<bool> Passenger_isChild { get; set; }
        public Nullable<System.DateTime> Passenger_Update_Date { get; set; }
        public bool isContactPassenger { get; set; }
        public string Passenger_MiddleName { get; set; }
        public string MilageNumber { get; set; }
        public string AirlineSeatPreferences { get; set; }
        public Nullable<bool> isSendNewsletter { get; set; }
        public Nullable<bool> isLeedTraveler { get; set; }
        public Nullable<double> Passenger_Deposit { get; set; }
        public string FrequentFlyerProgramName { get; set; }
        public string FrequentFlyerProgramNumber { get; set; }
        public string KnownTravelerNumber { get; set; }
        public string RedressNumber { get; set; }
        public Nullable<decimal> CancelationPrice { get; set; }
        public Nullable<decimal> ReductionPrice { get; set; }
        public string ReductionDesc { get; set; }
        public Nullable<int> Shipping_ID { get; set; }
    }
}
