//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp_Invoice
    {
        public int ID { get; set; }
        public Nullable<double> INVOICE_NO { get; set; }
        public Nullable<double> REF_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string INVOICE_IT { get; set; }
        public string DESCRIPTIO { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public string MODIFIED_I { get; set; }
        public string CREDIT_PAY { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
