//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp_Proposal_Oth_Supl_Cost
    {
        public int OTH_SER_ID { get; set; }
        public Nullable<int> Proposal_ID { get; set; }
        public Nullable<double> Ref_ID { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public Nullable<int> Supl_ID { get; set; }
        public string Date { get; set; }
        public string Service_Itinerary { get; set; }
        public string Country { get; set; }
        public string Supplier { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<int> Currency_ID { get; set; }
        public string Currency { get; set; }
        public Nullable<double> Size_1 { get; set; }
        public Nullable<double> Size_2 { get; set; }
        public Nullable<double> Size_3 { get; set; }
        public Nullable<double> Size_4 { get; set; }
        public Nullable<double> Size_5 { get; set; }
        public Nullable<double> Size_6 { get; set; }
        public Nullable<double> Sgl_Supl { get; set; }
        public Nullable<double> Price1 { get; set; }
        public Nullable<double> Price2 { get; set; }
        public Nullable<double> Price3 { get; set; }
        public Nullable<double> Price4 { get; set; }
        public Nullable<double> Price5 { get; set; }
        public Nullable<double> Price6 { get; set; }
        public Nullable<double> Sgl_Supl_Price { get; set; }
        public string Notes { get; set; }
        public Nullable<double> Size_1_Loc { get; set; }
        public Nullable<double> Size_2_Loc { get; set; }
        public Nullable<double> Size_3_Loc { get; set; }
        public Nullable<double> Size_4_Loc { get; set; }
        public Nullable<double> Size_5_Loc { get; set; }
        public Nullable<double> Size_6_Loc { get; set; }
        public Nullable<int> SupplierMarkUp { get; set; }
    }
}
