//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp_Proposal_GenExp_old
    {
        public int GENEXP_ID { get; set; }
        public Nullable<double> REFID { get; set; }
        public string GEN_SERVIC { get; set; }
        public Nullable<double> PRICE_NORM { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public string TRAVEL_PAX { get; set; }
        public string SERVICE_ST { get; set; }
        public string SERVICE_EN { get; set; }
        public Nullable<System.DateTime> SERVICE_S2 { get; set; }
        public Nullable<System.DateTime> SERVICE_E2 { get; set; }
        public string SERVICETM9 { get; set; }
        public string SERVICE_S3 { get; set; }
        public string MEAL { get; set; }
        public string NEED_BUS { get; set; }
        public string NEED_GUIDE { get; set; }
        public string NEED_ESCOR { get; set; }
        public Nullable<double> DAY { get; set; }
        public Nullable<double> PRICE_ALTE { get; set; }
        public string TIP_PERDAY { get; set; }
        public string GENEXP_ID2 { get; set; }
        public byte[] upsize_ts { get; set; }
        public Nullable<int> Start_Destination_ID { get; set; }
        public Nullable<int> End_Destination_ID { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
    }
}
