//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp_Cost_Supllier
    {
        public int ID { get; set; }
        public Nullable<double> COST_ID { get; set; }
        public Nullable<double> REF_ID { get; set; }
        public string SUPPLIER_N { get; set; }
        public Nullable<System.DateTime> CREATED_DA { get; set; }
        public string CREATEDTM9 { get; set; }
        public Nullable<System.DateTime> MODFIY_DAT { get; set; }
        public string MODIFY_TM9 { get; set; }
        public string DECRIPTION { get; set; }
        public Nullable<double> COST { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<double> EXC_RATE { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public string CREDIT_PAY { get; set; }
        public string CREATED_BY { get; set; }
        public string MODIFY_BY { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
