//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotePassenger2
    {
        public int QuotePassengerID { get; set; }
        public Nullable<int> ParentQuotePassengerID { get; set; }
        public int RefID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string SpecialRequest { get; set; }
        public Nullable<decimal> TravelInsurance { get; set; }
        public Nullable<double> Reduction { get; set; }
        public string RoomRequirement { get; set; }
        public Nullable<bool> Smoking { get; set; }
        public string Phone { get; set; }
        public string EmergencyContact { get; set; }
        public string VegeterianHealtRequirement { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<System.DateTime> InsuranceDate { get; set; }
        public bool IsInsuranceConfirmed { get; set; }
        public string EmergencyContactNo { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassportIssueDate { get; set; }
        public Nullable<System.DateTime> PassportExpirationDate { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Nationality { get; set; }
        public string Email { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public Nullable<decimal> QuoteReduction { get; set; }
        public Nullable<double> QuotePerPerson { get; set; }
        public Nullable<bool> IsChild { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool IsContactPassenger { get; set; }
        public string MiddleName { get; set; }
        public string MilageNumber { get; set; }
        public string AirlineSeatPreferences { get; set; }
        public Nullable<bool> IsSendNewsletter { get; set; }
        public Nullable<bool> IsLeedTraveler { get; set; }
        public Nullable<double> Deposit { get; set; }
        public string FrequentFlyerProgramName { get; set; }
        public string FrequentFlyerProgramNumber { get; set; }
        public string KnownTravelerNumber { get; set; }
        public string RedressNumber { get; set; }
        public Nullable<decimal> CancelationPrice { get; set; }
        public Nullable<decimal> ReductionPrice { get; set; }
        public string ReductionDesc { get; set; }
        public Nullable<int> ShippingID { get; set; }
        public string RedressIssuanceCountry { get; set; }
        public string RedressValidityCountry { get; set; }
        public string PassportIssuanceCountry { get; set; }
        public string PassportIssuanceCity { get; set; }
        public Nullable<int> PhoneCountryCode { get; set; }
        public Nullable<int> EmergencyPhoneCountryCode { get; set; }
    }
}
