//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp_Names
    {
        public int Name_ID { get; set; }
        public Nullable<int> Name_No { get; set; }
        public Nullable<int> Ref_ID { get; set; }
        public string Name_1 { get; set; }
        public string Remark { get; set; }
        public string Add_On { get; set; }
        public string RoomType { get; set; }
        public string Name_2 { get; set; }
        public string Name_3 { get; set; }
        public string Pax { get; set; }
        public Nullable<bool> Insurance { get; set; }
        public string INSURANCE_ { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
