//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp
    {
        public int Quotegrp_ID { get; set; }
        public Nullable<double> Ref_ID { get; set; }
        public Nullable<double> Custom_ID { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Room { get; set; }
        public Nullable<double> Increment { get; set; }
        public Nullable<System.DateTime> crc_Date { get; set; }
        public string crc_Agent { get; set; }
        public string Destination { get; set; }
        public string Contact { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public string Modify_By { get; set; }
        public string Group_Name { get; set; }
        public string Tour_Code { get; set; }
        public Nullable<double> Group_Min { get; set; }
        public Nullable<double> Land_Free { get; set; }
        public Nullable<double> Land_Free_Reque { get; set; }
        public Nullable<double> Comm { get; set; }
        public Nullable<double> Pax { get; set; }
        public Nullable<double> Group_Size { get; set; }
        public Nullable<double> Tip_Per_Day { get; set; }
        public string Lan_Supplier { get; set; }
        public string Remarks { get; set; }
        public string Notes { get; set; }
        public string Supplier { get; set; }
        public string Validiy { get; set; }
        public string Dep_City { get; set; }
        public string Ret_City { get; set; }
        public Nullable<double> MarkUp { get; set; }
        public string Tour_Guide { get; set; }
        public string Tour_Bus { get; set; }
        public string Refered_By { get; set; }
        public Nullable<double> Air_Free_Reque { get; set; }
        public string Free_Calculation { get; set; }
        public string Info_Detail { get; set; }
        public Nullable<double> Air_Tax { get; set; }
        public Nullable<double> Harbor_Tax { get; set; }
        public Nullable<double> Exchange { get; set; }
        public string DETAISL_OF { get; set; }
        public Nullable<int> BookingAgent_ID { get; set; }
        public string StatusID { get; set; }
        public Nullable<System.DateTime> Crt_Date { get; set; }
        public Nullable<int> Web_User_ID { get; set; }
        public string StartDestID { get; set; }
        public string EndDestID { get; set; }
    }
}
