//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotegrp_Proposal_Service
    {
        public int SERVICE_ID { get; set; }
        public Nullable<int> Proposal_ID { get; set; }
        public Nullable<int> REF_ID { get; set; }
        public Nullable<int> Tour_ID { get; set; }
        public Nullable<int> City_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<double> NIGHT { get; set; }
        public string CODE { get; set; }
        public Nullable<int> Supl_ID { get; set; }
        public string SUPPLIER { get; set; }
        public string DETAILS { get; set; }
        public Nullable<double> PRICE_DBL { get; set; }
        public Nullable<double> PRICE_SGL { get; set; }
        public string ROOM { get; set; }
        public Nullable<double> PAX { get; set; }
        public string MEAL { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public string DAY { get; set; }
        public string STATUS { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<double> DINNER { get; set; }
        public Nullable<double> LUNCH { get; set; }
        public Nullable<double> MUSEUM { get; set; }
        public Nullable<double> OTHERS { get; set; }
        public Nullable<double> CREW { get; set; }
        public string ROUTE { get; set; }
        public string ADD_INFO { get; set; }
        public string DINNER_DET { get; set; }
        public string LUNCH_DETA { get; set; }
        public string OTHERS_DET { get; set; }
        public string TOUR_CODE { get; set; }
        public Nullable<System.DateTime> SERV_MODFY { get; set; }
        public string SERV_MODIF { get; set; }
        public bool isNoService { get; set; }
    }
}
