//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public int RefID { get; set; }
        public int CompanyID { get; set; }
        public int MemberID { get; set; }
        public int BookingAgentID { get; set; }
        public Nullable<int> ConsumerID { get; set; }
        public int QuoteTypeID { get; set; }
        public Nullable<int> ShippingID { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public int Pax { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<int> ModifiedUserID { get; set; }
        public int CreatedUserID { get; set; }
        public string QuoteName { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<decimal> TotalServicePrice { get; set; }
        public Nullable<decimal> DepositPrice { get; set; }
        public Nullable<System.DateTime> DepositPaymentDueDate { get; set; }
        public Nullable<System.DateTime> FullPaymentDueDate { get; set; }
        public string InternalNotes { get; set; }
        public string SupplierMemo { get; set; }
        public string UserNotes { get; set; }
        public int PaymentRuleProfileID { get; set; }
        public Nullable<decimal> TripPrice { get; set; }
        public Nullable<decimal> InsuranceAmount { get; set; }
        public Nullable<decimal> ServiceCommissionPrice { get; set; }
        public Nullable<decimal> InsuranceCommissionPrice { get; set; }
        public bool IsInsuranceConfirmed { get; set; }
        public bool IsInsurancePaid { get; set; }
        public Nullable<System.DateTime> InsuranceConfirmDate { get; set; }
        public bool IsCommissionAppliedToPayment { get; set; }
        public Nullable<System.DateTime> CommissionAppliedToPaymentDate { get; set; }
        public Nullable<decimal> AddOnCommissionPrice { get; set; }
        public Nullable<System.DateTime> StatusChangeDate { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public Nullable<decimal> CancellationPrice { get; set; }
        public string CancellationDetail { get; set; }
        public Nullable<decimal> RevisionPrice { get; set; }
        public string RevisionDetail { get; set; }
        public string PromotionCode { get; set; }
        public Nullable<bool> IsCommissionPaymentDone { get; set; }
        public Nullable<decimal> TotalFlightPrice { get; set; }
        public bool IsDisplayNetPriceToAgents { get; set; }
        public bool IsReferral { get; set; }
        public Nullable<int> ReferralCompanyID { get; set; }
        public bool IsPointApplied { get; set; }
        public bool IsSentPostTrip { get; set; }
        public bool IsSentPaymentFull { get; set; }
        public bool IsSentPaymentDeposit { get; set; }
        public bool IsSentTravelDocument { get; set; }
        public Nullable<decimal> PromotionCommissionAdd { get; set; }
        public bool IsShowPriceOnTripDetail { get; set; }
        public bool IsShowCommisionOnTripDetail { get; set; }
        public bool IsBuyOnMiniWebSiteDisabled { get; set; }
    }
}
