//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referrer
    {
        public int Referrer_ID { get; set; }
        public Nullable<int> Visitors_Sent { get; set; }
        public Nullable<int> Bookings { get; set; }
    }
}
