//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResetPassword
    {
        public int ResetID { get; set; }
        public int Web_User_ID { get; set; }
        public System.Guid ResetKey { get; set; }
        public System.DateTime Date { get; set; }
        public bool isActive { get; set; }
    }
}
