//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendPaymentRequest
    {
        public Nullable<int> Ref_id { get; set; }
        public string LastName { get; set; }
        public string ZipCode { get; set; }
        public string RandomString { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> Web_User_Id { get; set; }
        public Nullable<int> Cust_ID { get; set; }
        public Nullable<int> UserProfile_ID { get; set; }
        public string WebUser_UserType { get; set; }
        public string SendEmail { get; set; }
        public Nullable<System.DateTime> RequestEndDate { get; set; }
        public int ID { get; set; }
    }
}
