//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceReview
    {
        public int ServiceReviewId { get; set; }
        public Nullable<int> ParcesHotelId { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string Review { get; set; }
        public string AuthorName { get; set; }
        public string AuthorPhotoUrl { get; set; }
        public string RelativeTimeDescription { get; set; }
        public string Language { get; set; }
        public Nullable<bool> isTraslated { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
    }
}
