//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRoomingPrice
    {
        public int ServiceRoomingPriceID { get; set; }
        public int ServiceID { get; set; }
        public int HotelRoomTypeID { get; set; }
        public decimal PricePerPerson { get; set; }
    }
}
