//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Old
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service_Old()
        {
            this.tbl_InvoiceServices = new HashSet<tbl_InvoiceServices>();
        }
    
        public int Service_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Night { get; set; }
        public string Tour_Item { get; set; }
        public string Service_Type { get; set; }
        public string Service_City { get; set; }
        public string Supplier { get; set; }
        public string Details { get; set; }
        public Nullable<decimal> Price_Dbl { get; set; }
        public Nullable<decimal> Price_SglSpl { get; set; }
        public Nullable<decimal> Service_TriplePrice { get; set; }
        public string Room { get; set; }
        public Nullable<int> Pax { get; set; }
        public string Commission { get; set; }
        public string Meal { get; set; }
        public string Reduction { get; set; }
        public string City { get; set; }
        public Nullable<int> Destination_ID { get; set; }
        public Nullable<int> Ref_ID { get; set; }
        public string Country { get; set; }
        public Nullable<int> Day { get; set; }
        public string Status { get; set; }
        public string StatusOnline { get; set; }
        public string Tour_Code { get; set; }
        public string Modf_By { get; set; }
        public Nullable<System.DateTime> Modf_Date { get; set; }
        public Nullable<int> Tour_ID { get; set; }
        public Nullable<int> Booking_Agent_ID { get; set; }
        public string Supl_Memo { get; set; }
        public Nullable<int> Supl_ID { get; set; }
        public Nullable<double> Supl_Price { get; set; }
        public Nullable<int> Air_ID { get; set; }
        public Nullable<double> Mark_Up { get; set; }
        public Nullable<int> Service_NumSingleRooms { get; set; }
        public Nullable<int> Service_NumDoubleRooms { get; set; }
        public Nullable<int> Service_NumTripleRooms { get; set; }
        public Nullable<int> Service_NumDoubleBedRooms { get; set; }
        public Nullable<decimal> Service_PrivateTourPrice { get; set; }
        public Nullable<int> Tour_Service_List_ID { get; set; }
        public Nullable<decimal> Service_HotelListAddOnPrice { get; set; }
        public string Service_PromotionDescription { get; set; }
        public string Service_PromotionDiscountType { get; set; }
        public Nullable<double> Service_PromotionDiscountValue { get; set; }
        public Nullable<int> Parent_Service_ID { get; set; }
        public Nullable<int> Service_NumOnRequest { get; set; }
        public string Service_SpecialNotes { get; set; }
        public string Service_PickupPoint { get; set; }
        public string Service_PickupTime { get; set; }
        public string Service_DropoffPoint { get; set; }
        public string Service_DropoffTime { get; set; }
        public Nullable<int> Service_LandOnlyPassengers { get; set; }
        public string Service_PickupDetail { get; set; }
        public Nullable<bool> Service_IsRowDeleted { get; set; }
        public Nullable<int> Service_ModifiedBy { get; set; }
        public Nullable<System.DateTime> Service_CreationDate { get; set; }
        public Nullable<System.DateTime> Service_ModificationDate { get; set; }
        public Nullable<short> Service_ModificationType { get; set; }
        public string Service_Time { get; set; }
        public Nullable<System.DateTime> Service_ModificationTime { get; set; }
        public Nullable<int> Service_AirOnRequest { get; set; }
        public Nullable<int> Service_NonSmokingRoom { get; set; }
        public string Service_BedType { get; set; }
        public Nullable<int> Service_CruiseOnRequest { get; set; }
        public Nullable<int> Service_PassengersOnPromotion { get; set; }
        public Nullable<double> Service_PassengerAgeReductions { get; set; }
        public Nullable<double> Service_PromotionReductions { get; set; }
        public Nullable<int> HotelClassID { get; set; }
        public string Service_InternalNotes { get; set; }
        public Nullable<bool> landonly { get; set; }
        public Nullable<bool> sent_item { get; set; }
        public Nullable<System.DateTime> sent_date { get; set; }
        public Nullable<System.DateTime> sent_time { get; set; }
        public string ServiceTicketName { get; set; }
        public string SupplierOperated { get; set; }
        public string SupplierBook { get; set; }
        public string ticketservicenotes { get; set; }
        public string ticketdetails { get; set; }
        public string tickettime1 { get; set; }
        public string tikettime2 { get; set; }
        public string ticketInternalNotes { get; set; }
        public string ticketdescription { get; set; }
        public string ticduration { get; set; }
        public string ticcategory { get; set; }
        public string ticpicture { get; set; }
        public Nullable<int> appendlog { get; set; }
        public Nullable<int> VoucherManuel { get; set; }
        public string Doiserno { get; set; }
        public Nullable<decimal> ServicePricePerPerson { get; set; }
        public Nullable<double> ServicePrice { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public Nullable<double> CommissionPrice { get; set; }
        public string Service_Board { get; set; }
        public Nullable<int> OnlineTime { get; set; }
        public string LocatorId { get; set; }
        public Nullable<double> AirPrice { get; set; }
        public string AirCommission { get; set; }
        public string XMLSupplier { get; set; }
        public string XMLRef { get; set; }
        public Nullable<int> RevisionTransaction { get; set; }
        public Nullable<double> PriceNetUsd { get; set; }
        public Nullable<double> PriceNetLocal { get; set; }
        public Nullable<int> PriceNetLocCurID { get; set; }
        public Nullable<double> RateAmount { get; set; }
        public Nullable<int> OnlineHotelID { get; set; }
        public Nullable<int> ParentSuplID { get; set; }
        public Nullable<int> OperatedSuplID { get; set; }
        public string ItemNumber { get; set; }
        public string GTALocator { get; set; }
        public Nullable<double> G_DoublePrice { get; set; }
        public Nullable<double> G_TriplePrice { get; set; }
        public Nullable<double> G_SinglePrice { get; set; }
        public Nullable<double> G_TwinPrice { get; set; }
        public Nullable<int> G_DoubleNr { get; set; }
        public Nullable<int> G_SingleNr { get; set; }
        public Nullable<int> G_TripleNr { get; set; }
        public Nullable<int> G_TwinNr { get; set; }
        public decimal SinglePrice { get; set; }
        public decimal DoublePrice { get; set; }
        public decimal TwinPrice { get; set; }
        public decimal TriplePrice { get; set; }
        public byte ChildCount { get; set; }
        public Nullable<int> tbl_Invoice_ID { get; set; }
        public string Duration { get; set; }
        public string Service_PassengerInfo { get; set; }
        public bool Service_HasPromo { get; set; }
        public bool Service_PassengerUpdated { get; set; }
        public string Service_CalculationNotes { get; set; }
        public bool isNew { get; set; }
        public Nullable<System.DateTime> HotelConfirmExpirationDate { get; set; }
        public bool isHidden { get; set; }
        public Nullable<bool> isNonRefundable { get; set; }
        public string TF_RoutingID { get; set; }
        public string TF_OutwardID { get; set; }
        public string TF_ReturnID { get; set; }
        public string TF_ProcessDetailsMsg { get; set; }
        public Nullable<int> Service_Origin { get; set; }
        public Nullable<decimal> TF_ExpectedServicePriceAmount { get; set; }
        public string TF_ExpectedServicePriceCurrency { get; set; }
        public string TF_BookingReference { get; set; }
        public Nullable<System.DateTime> TF_CheckBookingStartDate { get; set; }
        public string TF_ProcessDetailsBookingOptions { get; set; }
        public Nullable<decimal> TF_ServiceAddOnNet { get; set; }
        public Nullable<decimal> TF_ServiceAddOnGross { get; set; }
        public string TF_TicketNumber { get; set; }
        public Nullable<int> Service_NumQuadRooms { get; set; }
        public Nullable<decimal> QuadPrice { get; set; }
        public string TC_Token { get; set; }
        public Nullable<int> ProviderCode { get; set; }
        public bool TF_IsPrepay { get; set; }
        public string AE_QuoteID { get; set; }
        public string AE_SIPP { get; set; }
        public string AE_Airline { get; set; }
        public string AE_FligtNumber { get; set; }
        public Nullable<int> AE_Passengers { get; set; }
        public bool IsAdditionalInfoEntered { get; set; }
        public string ViatorAdditionalInput { get; set; }
        public string AmadeusPriceCheckResponse { get; set; }
        public string AmadeusCreateOrderRequest { get; set; }
        public string AmadeusCreateOrderResponse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InvoiceServices> tbl_InvoiceServices { get; set; }
    }
}
