//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceNetPriceBreakdown
    {
        public int ServiceNetPriceBreakdownID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<int> ServiceHotelRoomID { get; set; }
        public int ApiUserID { get; set; }
        public decimal NetPriceInUSD { get; set; }
        public decimal NetPriceInLocalCurrency { get; set; }
        public int NetPriceCurrencyID { get; set; }
        public decimal NetPriceExchangeRateAmount { get; set; }
    }
}
