//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceHotelRoom2
    {
        public int ServiceHotelRoomID { get; set; }
        public int ServiceID { get; set; }
        public string RoomName { get; set; }
        public string MealShort { get; set; }
        public string Meal { get; set; }
        public string ProviderSelectedOption { get; set; }
        public decimal RoomPrice { get; set; }
        public decimal RoomPriceNet { get; set; }
        public int HotelRoomTypeID { get; set; }
        public bool isRefundable { get; set; }
        public string SubProviderCode { get; set; }
        public Nullable<int> ProviderCode { get; set; }
        public string ConfirmationNumber { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
    }
}
