//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Revision_Log
    {
        public int LOGID { get; set; }
        public Nullable<int> Ref_ID { get; set; }
        public Nullable<int> Service_ID { get; set; }
        public Nullable<decimal> RevisionAmount { get; set; }
        public string RevisionNote { get; set; }
        public Nullable<int> Booking_Agent { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> serviceoldprice { get; set; }
        public Nullable<decimal> serviceOldComm { get; set; }
        public Nullable<System.DateTime> serviceolddate { get; set; }
        public Nullable<int> serviceoldpax { get; set; }
        public string serviceOldName { get; set; }
        public Nullable<int> serviceOldTour_ID { get; set; }
        public Nullable<int> serviceOldSupl_ID { get; set; }
        public string revisionType { get; set; }
        public string RevisionNoteDetail { get; set; }
        public Nullable<int> LogVisible { get; set; }
    }
}
