//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service2
    {
        public int ServiceID { get; set; }
        public int RefID { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public int ServiceTypeID { get; set; }
        public string ServiceName { get; set; }
        public string Detail { get; set; }
        public int Pax { get; set; }
        public int ChildCount { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public int ServiceStatusID { get; set; }
        public Nullable<int> TourID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> ParentServiceID { get; set; }
        public Nullable<int> TourServiceListID { get; set; }
        public Nullable<int> ModifiedUserID { get; set; }
        public Nullable<int> CratedUserID { get; set; }
        public Nullable<int> ParentSupplierID { get; set; }
        public Nullable<int> OperatedSupplierID { get; set; }
        public Nullable<int> ParsecHotelID { get; set; }
        public string ProviderID { get; set; }
        public int ProviderCode { get; set; }
        public string ProviderConfirmationNumber { get; set; }
        public Nullable<System.DateTime> ProviderConfirmedDate { get; set; }
        public string ProviderSelectedOption { get; set; }
        public string SupplierNote { get; set; }
        public string InternalNotes { get; set; }
        public string SpecialNotes { get; set; }
        public string PriceCalculationNotes { get; set; }
        public string PickupLocationID { get; set; }
        public string PickupPoint { get; set; }
        public Nullable<System.DateTime> PickupPointTime { get; set; }
        public string DropoffLocationID { get; set; }
        public string DropoffPoint { get; set; }
        public Nullable<System.DateTime> DropoffPointTime { get; set; }
        public string PickupDetail { get; set; }
        public string Duration { get; set; }
        public decimal ServicePrice { get; set; }
        public Nullable<decimal> ServicePricePerPerson { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public Nullable<decimal> CommissionPrice { get; set; }
        public Nullable<int> CommissionRate { get; set; }
        public decimal NetPriceInUSD { get; set; }
        public decimal NetPriceInLocalCurrency { get; set; }
        public int NetPriceCurrencyID { get; set; }
        public decimal NetPriceExchangeRateAmount { get; set; }
        public string PromotionDiscountType { get; set; }
        public Nullable<decimal> PromotionDiscountValue { get; set; }
        public Nullable<decimal> PromotionDiscountAmount { get; set; }
        public string PassengerInfo { get; set; }
        public int ServiceOriginID { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> SupplierNotificationSendDate { get; set; }
        public Nullable<System.DateTime> HotelConfirmExpirationDate { get; set; }
        public bool IsHidden { get; set; }
        public bool IsAdditionalService { get; set; }
        public Nullable<bool> IsRefundable { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<decimal> PrivateTourPrice { get; set; }
        public Nullable<bool> hasMismatchedRoomTypes { get; set; }
    }
}
