//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePassenger2
    {
        public int ServicePassengerID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<int> ServiceHotelRoomID { get; set; }
        public Nullable<int> QuotePassengerID { get; set; }
        public string RoomType { get; set; }
        public Nullable<int> RoomNumber { get; set; }
        public Nullable<int> CruiseCabinID { get; set; }
        public Nullable<decimal> CruiseCabinUpgradePrice { get; set; }
        public string FlightNoOrCruiseLineIn { get; set; }
        public string FlightNoOrCruiseLineOut { get; set; }
        public Nullable<int> CruiseOnRequest { get; set; }
        public Nullable<double> PricePerPerson { get; set; }
        public string ServiceOptions { get; set; }
        public Nullable<decimal> ServiceOptionsAddOnNet { get; set; }
        public Nullable<decimal> ServiceOptionsAddOnGross { get; set; }
        public string AgeBand { get; set; }
    }
}
