//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProfitBreakdown
    {
        public int ServiceProfitBreakdownID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<int> ServiceHotelRoomID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<decimal> ProfitPrice { get; set; }
    }
}
