//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCategory
    {
        public int Service_Category_ID { get; set; }
        public Nullable<int> Parent_Service_Category_ID { get; set; }
        public string ServiceCategory_Name { get; set; }
        public string ServiceCategory_Description { get; set; }
        public string ServiceCategory_ProductType { get; set; }
        public Nullable<int> ServiceCategory_Level { get; set; }
        public string ServiceCategory_Page { get; set; }
        public Nullable<bool> ServiceCategory_DisplayInList { get; set; }
        public string ServiceCategory_Icon { get; set; }
        public string ServiceCategory_PageNew { get; set; }
        public Nullable<bool> isDisplayGroup { get; set; }
    }
}
