//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceType()
        {
            this.CancelationRuleSubConditions = new HashSet<CancelationRuleSubCondition>();
            this.MarkupRules = new HashSet<MarkupRule>();
            this.PaymentRuleSubConditions = new HashSet<PaymentRuleSubCondition>();
        }
    
        public byte ServiceTypeId { get; set; }
        public string ServiceTypeName { get; set; }
        public bool HasRooming { get; set; }
        public bool hideOnAdditionalService { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelationRuleSubCondition> CancelationRuleSubConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarkupRule> MarkupRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRuleSubCondition> PaymentRuleSubConditions { get; set; }
    }
}
