//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int ShoppingCartID { get; set; }
        public System.Guid TempCustomerID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public int ServiceOrigin { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public string ProviderID { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public int ProviderCode { get; set; }
        public string ProviderSelectedOption { get; set; }
        public Nullable<int> TourServiceListID { get; set; }
        public Nullable<int> TourID { get; set; }
        public Nullable<int> ParsecHotelID { get; set; }
        public Nullable<int> CruiseCabinID { get; set; }
        public int DestinationID { get; set; }
        public Nullable<bool> isPrivateTour { get; set; }
        public Nullable<bool> isRefundable { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public string Duration { get; set; }
        public int Pax { get; set; }
        public int ChildCount { get; set; }
        public string PassengerInfo { get; set; }
        public Nullable<decimal> ServicePrice { get; set; }
        public Nullable<int> NumSingleRooms { get; set; }
        public Nullable<int> NumDoubleRooms { get; set; }
        public Nullable<int> NumTripleRooms { get; set; }
        public Nullable<int> NumQuadRooms { get; set; }
        public Nullable<int> NumTwinRooms { get; set; }
        public string PickupDetail { get; set; }
        public string PickupPoint { get; set; }
        public Nullable<System.DateTime> PickupPointTime { get; set; }
        public string DropoffPoint { get; set; }
        public Nullable<System.DateTime> DropoffPointTime { get; set; }
        public string PickupLocationID { get; set; }
        public string DropoffLocationID { get; set; }
        public string Thumbnail { get; set; }
        public string PromotionDiscountType { get; set; }
        public Nullable<decimal> PromotionDiscountValue { get; set; }
        public Nullable<decimal> PromotionReductions { get; set; }
        public bool isDeleted { get; set; }
    }
}
