//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaticPage
    {
        public int StaticPageID { get; set; }
        public int ApiUserId { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public int StaticPageTypeID { get; set; }
        public string PageCaption { get; set; }
        public string PageCaptionBottom { get; set; }
        public string PageText { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string SeoKeywords { get; set; }
        public string VisibleUrl { get; set; }
        public string ExternalLink { get; set; }
        public bool ShowOnFooter { get; set; }
        public bool ShowOnHeader { get; set; }
        public int SortOrder { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ApiUser ApiUser { get; set; }
        public virtual StaticPageType StaticPageType { get; set; }
    }
}
