//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubService
    {
        public int SubServiceID { get; set; }
        public int ServiceID { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public int ServiceTypeID { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> ParentSupplierID { get; set; }
        public Nullable<int> TourID { get; set; }
        public Nullable<int> OperatedSupplierID { get; set; }
        public string PickupPoint { get; set; }
        public Nullable<System.DateTime> PickupPointTime { get; set; }
        public string DropoffPoint { get; set; }
        public Nullable<System.DateTime> DropoffPointTime { get; set; }
        public string InternalNotes { get; set; }
    }
}
