//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSupplier
    {
        public int ID { get; set; }
        public int SupplierID { get; set; }
        public int SubSupplierTypeID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string ContactPerson { get; set; }
        public string MobilePhone { get; set; }
        public string EmergencyPhone { get; set; }
        public string Email { get; set; }
        public string PlateNumber { get; set; }
        public bool isActive { get; set; }
    
        public virtual SubSupplierType SubSupplierType { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
