//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suplierb_Tmp
    {
        public int Supl_ID { get; set; }
        public string Rate_Type { get; set; }
        public Nullable<System.DateTime> Fm_1 { get; set; }
        public Nullable<System.DateTime> To_1 { get; set; }
        public Nullable<double> Dbl_PP_Net { get; set; }
        public Nullable<double> SglSpl_Net { get; set; }
        public Nullable<double> Trp_PP_Net { get; set; }
        public string Board { get; set; }
        public string Room_Type { get; set; }
        public Nullable<double> Mark_Up { get; set; }
        public Nullable<double> Meal_Net { get; set; }
        public int Suppb_ID { get; set; }
        public string Modf_By { get; set; }
        public Nullable<System.DateTime> Modf_Date { get; set; }
        public string Addl_Note { get; set; }
        public Nullable<double> Dbl_PP_Gross { get; set; }
        public Nullable<double> Sgl_Supl_Gross { get; set; }
        public Nullable<double> Trp_PP_Gross { get; set; }
        public Nullable<int> Suplierb_Allotment { get; set; }
        public Nullable<int> Suplierb_AlertValue { get; set; }
        public Nullable<int> Suplierb_DaysBefore { get; set; }
        public Nullable<int> Suplierb_CurType { get; set; }
        public string Suplierb_DateRangeName { get; set; }
        public Nullable<bool> Suplierb_RunOnSun { get; set; }
        public Nullable<bool> Suplierb_RunOnMon { get; set; }
        public Nullable<bool> Suplierb_RunOnTue { get; set; }
        public Nullable<bool> Suplierb_RunOnWed { get; set; }
        public Nullable<bool> Suplierb_RunOnThu { get; set; }
        public Nullable<bool> Suplierb_RunOnFri { get; set; }
        public Nullable<bool> Suplierb_RunOnSat { get; set; }
        public Nullable<bool> specialRate { get; set; }
        public string CheckIn_Time { get; set; }
        public string checkOut_Time { get; set; }
        public Nullable<int> ChildType1_FM { get; set; }
        public Nullable<int> ChildType1_To { get; set; }
        public Nullable<double> ChildType1_Gross { get; set; }
        public Nullable<double> ChildType1_Net { get; set; }
        public Nullable<int> ChildType2_FM { get; set; }
        public Nullable<int> ChildType2_To { get; set; }
        public Nullable<double> ChildType2_Gross { get; set; }
        public Nullable<double> ChildType2_Net { get; set; }
        public string Days { get; set; }
    }
}
