//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierCabin
    {
        public int Supl_ID { get; set; }
        public int Cruise_Cabin_ID { get; set; }
        public string Cabin_Name { get; set; }
        public string Cabin_Descriptionext { get; set; }
        public Nullable<bool> Cabin_Exist { get; set; }
        public int USID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CruiseCabin CruiseCabin { get; set; }
    }
}
