//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class suppl_sent_log
    {
        public long auto_id { get; set; }
        public Nullable<System.DateTime> sent_date { get; set; }
        public Nullable<System.DateTime> sent_time { get; set; }
        public Nullable<long> session_id { get; set; }
        public Nullable<int> ref_id { get; set; }
        public string Supl_Name { get; set; }
        public Nullable<int> P_Supl_ID { get; set; }
        public string E_Mail { get; set; }
        public Nullable<int> Tour_ID { get; set; }
        public Nullable<int> Supl_ID { get; set; }
        public Nullable<int> Service_ID { get; set; }
        public string Tour_Item { get; set; }
        public Nullable<int> Night { get; set; }
        public string Supplier { get; set; }
        public Nullable<int> Pax { get; set; }
        public Nullable<int> Service_NonSmokingRoom { get; set; }
        public string Service_BedType { get; set; }
        public string Service_SpecialNotes { get; set; }
        public string Supl_Memo { get; set; }
        public Nullable<int> Service_NumSingleRooms { get; set; }
        public Nullable<int> Service_NumDoubleRooms { get; set; }
        public Nullable<int> Service_NumTripleRooms { get; set; }
        public Nullable<System.DateTime> ServiceStartDate { get; set; }
        public string Service_Time { get; set; }
        public string Service_PickupPoint { get; set; }
        public string Service_DropoffPoint { get; set; }
        public string Service_PickupDetail { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> TripStartDate { get; set; }
        public string Quote_Name { get; set; }
        public string Quote_SupplierMemo { get; set; }
        public string Destination_Name { get; set; }
        public string ServiceCategory_Name { get; set; }
        public Nullable<int> parent_service_id { get; set; }
        public string txtsuppliernotes { get; set; }
        public Nullable<short> Service_ModificationType { get; set; }
        public Nullable<bool> Service_IsRowDeleted { get; set; }
        public Nullable<bool> sent_item { get; set; }
        public string room { get; set; }
        public string SupplierAllotment_Board { get; set; }
        public Nullable<bool> admin { get; set; }
        public Nullable<decimal> Service_PrivateTourPrice { get; set; }
        public Nullable<int> ownID { get; set; }
        public string serviceDay { get; set; }
        public string passangersStr { get; set; }
        public string bookingType { get; set; }
    }
}
