//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierAllotment
    {
        public int Supplier_Allotment_ID { get; set; }
        public Nullable<int> Allotment_Source_Supplier_ID { get; set; }
        public int Supl_ID { get; set; }
        public Nullable<int> Suppb_ID { get; set; }
        public Nullable<System.DateTime> SupplierAllotment_Date { get; set; }
        public Nullable<System.DateTime> SupplierAllotment_CancelReminderDate { get; set; }
        public string SupplierAllotment_RoomType { get; set; }
        public Nullable<int> SupplierAllotment_Total { get; set; }
        public Nullable<int> SupplierAllotment_Booked { get; set; }
        public Nullable<int> SupplierAllotment_Cancel { get; set; }
        public string SupplierAllotment_RateType { get; set; }
        public Nullable<double> SupplierAllotment_DoublePerPersonNet { get; set; }
        public Nullable<double> SupplierAllotment_TriplePerPersonNet { get; set; }
        public Nullable<double> SupplierAllotment_MealNet { get; set; }
        public Nullable<double> SupplierAllotment_DoublePerPersonGross { get; set; }
        public Nullable<double> SupplierAllotment_TriplePerPersonGross { get; set; }
        public Nullable<double> SupplierAllotment_MarkUp { get; set; }
        public string SupplierAllotment_Board { get; set; }
        public Nullable<int> SupplierAllotment_SingleBooked { get; set; }
        public Nullable<int> SupplierAllotment_DoubleBooked { get; set; }
        public Nullable<int> SupplierAllotment_TripleBooked { get; set; }
        public Nullable<double> SupplierAllotment_SingleSupplPerPersonNet { get; set; }
        public Nullable<double> SupplierAllotment_SingleSupplPerPersonGross { get; set; }
        public Nullable<int> SupplierAllotment_AlertValue { get; set; }
        public Nullable<int> SupplierAllotment_CurType { get; set; }
        public Nullable<byte> SupplierAllotment_ChildType1_FM { get; set; }
        public Nullable<byte> SupplierAllotment_ChildType1_To { get; set; }
        public Nullable<double> SupplierAllotment_ChildType1_Gross { get; set; }
        public Nullable<double> SupplierAllotment_ChildType1_Net { get; set; }
        public Nullable<byte> SupplierAllotment_ChildType2_FM { get; set; }
        public Nullable<byte> SupplierAllotment_ChildType2_To { get; set; }
        public Nullable<double> SupplierAllotment_ChildType2_Gross { get; set; }
        public Nullable<double> SupplierAllotment_ChildType2_Net { get; set; }
        public int SupplierAllotment_QuadBooked { get; set; }
    }
}
