//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierPaymentRule
    {
        public int ID { get; set; }
        public int SupplierID { get; set; }
        public int RuleTypeID { get; set; }
        public Nullable<int> PaymentDueAdd { get; set; }
        public Nullable<int> ServiceDateFrom { get; set; }
        public Nullable<int> ServiceDateTo { get; set; }
        public Nullable<int> PaymentDueMonth { get; set; }
        public Nullable<int> PaymentDueDay { get; set; }
    }
}
