//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierResponse
    {
        public int ID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public int WebUserId { get; set; }
        public string PickUpPoint { get; set; }
        public Nullable<System.DateTime> PickUpTime { get; set; }
        public string DropOffPoint { get; set; }
        public Nullable<System.DateTime> DropOffTime { get; set; }
        public string AdditionalNotes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool isReviewed { get; set; }
        public Nullable<int> ReviewerAgentID { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> GuideID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> SubSupplierID { get; set; }
        public string RoomType { get; set; }
        public string Meal { get; set; }
        public string ConfirmationNumber { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public string FileUrl { get; set; }
        public string ticketNumber { get; set; }
        public string ticketCategory { get; set; }
    }
}
