//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierAddOnRate
    {
        public int Supl_ID { get; set; }
        public int Supplier_Add_On_Rate_ID { get; set; }
        public string SupplierAddOnRate_Description { get; set; }
        public Nullable<decimal> SupplierAddOnRate_Price { get; set; }
        public string SupplierAddOnRate_CabinDescription { get; set; }
    }
}
