//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierSuggestion
    {
        public int Supl_ID { get; set; }
        public int Suggested_Supl_ID { get; set; }
        public int SupplierSuggestion_RelationType { get; set; }
        public string SupplierSuggestion_RelationRank { get; set; }
    }
}
