//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.CancelationRuleSubConditions = new HashSet<CancelationRuleSubCondition>();
            this.PaymentRuleSubConditions = new HashSet<PaymentRuleSubCondition>();
            this.SubSuppliers = new HashSet<SubSupplier>();
            this.SupplierMembers = new HashSet<SupplierMember>();
        }
    
        public Nullable<int> Parent_Supl_ID { get; set; }
        public string Supl_Name { get; set; }
        public string Category { get; set; }
        public Nullable<int> Destination_ID { get; set; }
        public string Area { get; set; }
        public Nullable<int> Product_Category_ID { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Mark { get; set; }
        public int Supl_ID { get; set; }
        public string Contct_Pers { get; set; }
        public string Location { get; set; }
        public string No_Of_Room { get; set; }
        public string No_Of_Beds { get; set; }
        public Nullable<bool> A_C { get; set; }
        public Nullable<bool> Restaurant { get; set; }
        public Nullable<bool> Tv_Satilit { get; set; }
        public Nullable<bool> Indoor_Pool { get; set; }
        public Nullable<bool> Outdoor_Pool { get; set; }
        public Nullable<bool> Shopping_Arcade { get; set; }
        public Nullable<bool> Parking { get; set; }
        public string Meeting_Room { get; set; }
        public Nullable<bool> Laundry { get; set; }
        public Nullable<bool> Minibar { get; set; }
        public string Description { get; set; }
        public string Supl_Type { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<double> Exch_Rate { get; set; }
        public string Note_ForUs { get; set; }
        public string Luxury_EMail { get; set; }
        public string E_Mail { get; set; }
        public string Located { get; set; }
        public string Supl_Pict1 { get; set; }
        public string Supl_Pict2 { get; set; }
        public string Supl_Pict3 { get; set; }
        public Nullable<int> Service_Category_ID { get; set; }
        public string Supplier_UserName { get; set; }
        public string Supplier_Password { get; set; }
        public Nullable<bool> Supplier_DisplayOnWeb { get; set; }
        public Nullable<int> Supplier_Rating { get; set; }
        public string Supplier_Picture2 { get; set; }
        public string Supplier_Picture3 { get; set; }
        public string Supl_Thumbnail { get; set; }
        public string CheckIn_Time { get; set; }
        public string CheckOut_Time { get; set; }
        public string Telephone24Hours { get; set; }
        public Nullable<byte> MinorDirect { get; set; }
        public Nullable<int> DefaultRoomTypeID { get; set; }
        public Nullable<bool> Matching { get; set; }
        public Nullable<System.DateTime> PicUploadDate { get; set; }
        public string GeoCode { get; set; }
        public string XMLSupp { get; set; }
        public string LocalKey { get; set; }
        public string SeoTitle { get; set; }
        public string SeoKeywords { get; set; }
        public string SeoDescription { get; set; }
        public int PaymentTypeID { get; set; }
        public bool isDirectPayment { get; set; }
        public string AccountHolderFirstName { get; set; }
        public string AccountHolderLastName { get; set; }
        public string AccountType { get; set; }
        public string AccountNumber { get; set; }
        public string RoutingNumber { get; set; }
        public string AccountingEmail { get; set; }
        public bool isPreferred { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelationRuleSubCondition> CancelationRuleSubConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRuleSubCondition> PaymentRuleSubConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubSupplier> SubSuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierMember> SupplierMembers { get; set; }
    }
}
