//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskCheckPoint
    {
        public int TaskCheckPointID { get; set; }
        public int TaskID { get; set; }
        public int TaskTypeCheckPointOptionID { get; set; }
        public bool Value { get; set; }
    }
}
