//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDocumentControl
    {
        public int TaskDocumentControlID { get; set; }
        public int TaskID { get; set; }
        public bool AirTicket { get; set; }
        public bool Hotels { get; set; }
        public bool TrainTickets { get; set; }
        public bool Cruise { get; set; }
        public bool TransferDetails { get; set; }
    }
}
