//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskApiUser
    {
        public int TaskApiUserID { get; set; }
        public int ApiUserID { get; set; }
        public int TaskTypeID { get; set; }
        public Nullable<int> NextTaskTypeID { get; set; }
        public int MemberTypeID { get; set; }
        public int TaskDeadLine { get; set; }
        public bool isCreateWithQuote { get; set; }
        public bool isCreateWithTaskLead { get; set; }
    }
}
