//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskLead
    {
        public int TaskLeadID { get; set; }
        public int MemberID { get; set; }
        public int CompanyID { get; set; }
        public string PromotionCode { get; set; }
        public string Gateway { get; set; }
        public string PaxAndRoomNum { get; set; }
        public string RoomCategory { get; set; }
        public string Meal { get; set; }
        public string ItineraryNotes { get; set; }
        public string HubSpotDeallD { get; set; }
        public string Source { get; set; }
    }
}
