//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public int AgentID { get; set; }
        public Nullable<int> Ref_ID { get; set; }
        public Nullable<int> Pending_ID { get; set; }
        public int TaskLeadID { get; set; }
        public Nullable<int> PreviousTaskID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int TaskApiUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string Note { get; set; }
        public bool isCompleted { get; set; }
        public bool isActive { get; set; }
        public bool isWebService { get; set; }
        public Nullable<int> TaskCancelReasonID { get; set; }
        public string TaskCancelReasonNote { get; set; }
        public bool isAwaitClientDecision { get; set; }
        public bool isNew { get; set; }
    }
}
