//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Invoice()
        {
            this.tbl_InvoiceServices = new HashSet<tbl_InvoiceServices>();
        }
    
        public int InvoiceID { get; set; }
        public Nullable<int> SuplID { get; set; }
        public Nullable<int> InvoiceOrderID { get; set; }
        public Nullable<System.DateTime> crt_Date { get; set; }
        public Nullable<int> RefID { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public Nullable<bool> PaymentDone { get; set; }
        public Nullable<System.DateTime> ComfirmeDate { get; set; }
        public string ServiceType { get; set; }
        public string InvoiceNo { get; set; }
        public decimal Cost { get; set; }
        public decimal TotalCost { get; set; }
        public double Rate { get; set; }
        public string Status { get; set; }
        public string exp { get; set; }
        public Nullable<int> qty { get; set; }
        public string CurType { get; set; }
        public Nullable<int> PaidBy { get; set; }
        public Nullable<double> estimateCost { get; set; }
        public Nullable<double> EstimateTotalCost { get; set; }
        public string estimateCurType { get; set; }
        public Nullable<double> estimateRate { get; set; }
        public string CostComfirmNo { get; set; }
        public Nullable<System.DateTime> CostComfirmDate { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<System.DateTime> PaymentDoneDate { get; set; }
        public Nullable<int> CxpTransationID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InvoiceServices> tbl_InvoiceServices { get; set; }
    }
}
