//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InvoiceServices
    {
        public int ID { get; set; }
        public int InvoiceID { get; set; }
        public int ServiceID { get; set; }
    
        public virtual Service_Old Service_Old { get; set; }
        public virtual tbl_Invoice tbl_Invoice { get; set; }
    }
}
