//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateDesign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateDesign()
        {
            this.Companies = new HashSet<Company>();
        }
    
        public int TemplateDesignID { get; set; }
        public Nullable<int> TemplateOwnerCompanyID { get; set; }
        public string TemplateName { get; set; }
        public string FontPrimaryColor { get; set; }
        public string FontSecondaryColor { get; set; }
        public string PrimaryColor1 { get; set; }
        public string PrimaryColor2 { get; set; }
        public string SecondaryColor1 { get; set; }
        public string SecondaryColor2 { get; set; }
        public string SecondaryColor3 { get; set; }
        public string DarkFontPrimaryColor { get; set; }
        public string DarkFontSecondaryColor { get; set; }
        public string DarkPrimaryColor1 { get; set; }
        public string DarkPrimaryColor2 { get; set; }
        public string DarkSecondaryColor1 { get; set; }
        public string DarkSecondaryColor2 { get; set; }
        public string DarkSecondaryColor3 { get; set; }
        public bool IsDefault { get; set; }
        public string BackgroundColor1 { get; set; }
        public string BackgroundColor2 { get; set; }
        public string DarkBackgroundColor1 { get; set; }
        public string DarkBackgroundColor2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Companies { get; set; }
    }
}
