//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TfppPaymentsReturn
    {
        public int Ref_ID { get; set; }
        public Nullable<decimal> TripAmount { get; set; }
        public Nullable<decimal> LandOnlyAmount { get; set; }
        public Nullable<decimal> FlightNetAmount { get; set; }
        public Nullable<decimal> Arc_FlightAmount { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
    }
}
