//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmSequenceTaskTemplate
    {
        public int Id { get; set; }
        public int TmSequenceId { get; set; }
        public int TmTaskTemplateId { get; set; }
    
        public virtual TmSequence TmSequence { get; set; }
        public virtual TmTaskTemplate TmTaskTemplate { get; set; }
    }
}
