//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmTaskTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TmTaskTemplate()
        {
            this.TmSequenceTaskTemplates = new HashSet<TmSequenceTaskTemplate>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ValidForHours { get; set; }
        public int TmReferanceDateId { get; set; }
        public int TmReferanceEventId { get; set; }
        public int ReferanceTaskId { get; set; }
        public int TmCompleteActionId { get; set; }
        public int CompleteActionDelayHours { get; set; }
        public bool AutoCompleteWhenExpire { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TmSequenceTaskTemplate> TmSequenceTaskTemplates { get; set; }
    }
}
