//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourServiceList_Tour
    {
        public int Tour_ID { get; set; }
        public int Tour_Service_List_ID { get; set; }
        public int Service_Tour_ID { get; set; }
        public int TourServiceList_Tour_Day { get; set; }
        public string ViatorProductCode { get; set; }
        public Nullable<int> TourServiceList_Tour_Nights { get; set; }
        public Nullable<int> TourServiceList_Tour_ParentDay { get; set; }
        public Nullable<int> MainNotify { get; set; }
        public string CheckIntime { get; set; }
        public Nullable<int> DefaultList { get; set; }
        public Nullable<int> DestID { get; set; }
        public Nullable<int> PackageDestID { get; set; }
        public string PickUpLocation { get; set; }
        public string DropOffLocation { get; set; }
        public string DropOffTime { get; set; }
        public string CarSipp { get; set; }
        public string ViatorProductOption { get; set; }
    }
}
