//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourFlightSchedule
    {
        public int TourFlightSchedule_ID { get; set; }
        public int Tour_ID { get; set; }
        public int Tour_Schedule_ID { get; set; }
        public int Departure_City_ID { get; set; }
        public System.DateTime TourFlightSchedule_BeginDate { get; set; }
        public System.DateTime TourFlightSchedule_EndDate { get; set; }
        public Nullable<int> TourFlightSchedule_AddOnPrice { get; set; }
        public int TourFlightSchedule_TotalAllotment { get; set; }
        public Nullable<int> TourFlightSchedule_AlertValue { get; set; }
        public Nullable<int> TourFlightSchedule_DaysBefore { get; set; }
        public Nullable<int> TourFlightSchedule_AddOnPriceNet { get; set; }
        public Nullable<double> TourFlightSchedule_MarkUp { get; set; }
        public Nullable<int> TourFlightSchedule_CurType { get; set; }
        public Nullable<int> TourFlightSchedule_DestinationID { get; set; }
        public Nullable<int> TourFlightSchedule_AirLineID { get; set; }
    }
}
