//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourAllotment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TourAllotment()
        {
            this.TourFlightAllotments = new HashSet<TourFlightAllotment>();
        }
    
        public int Tour_Allotment_ID { get; set; }
        public int Tour_ID { get; set; }
        public System.DateTime TourAllotment_Date { get; set; }
        public Nullable<System.DateTime> TourAllotment_CancelReminderDate { get; set; }
        public Nullable<int> TourAllotment_Total { get; set; }
        public Nullable<int> TourAllotment_Booked { get; set; }
        public Nullable<int> TourAllotment_Cancel { get; set; }
        public Nullable<decimal> TourAllotment_BasePrice { get; set; }
        public Nullable<decimal> TourAllotment_SingleSupplement { get; set; }
        public Nullable<decimal> TourAllotment_TriplePrice { get; set; }
        public Nullable<decimal> TourAllotment_DeluxeHotelSupplement { get; set; }
        public Nullable<decimal> TourAllotment_DeluxeHotelSingleSupplement { get; set; }
        public Nullable<decimal> TourAllotment_MealSupplement { get; set; }
        public Nullable<int> TourAllotment_AlertValue { get; set; }
        public Nullable<int> Advse_Book_ID { get; set; }
        public Nullable<decimal> TourAllotment_BasePriceNet { get; set; }
        public Nullable<decimal> TourAllotment_SingleSupplementNet { get; set; }
        public Nullable<decimal> TourAllotment_TriplePriceNet { get; set; }
        public Nullable<decimal> TourAllotment_DeluxeHotelSupplementNet { get; set; }
        public Nullable<decimal> TourAllotment_DeluxeHotelSingleSupplementNet { get; set; }
        public Nullable<double> TourAllotment_Markup { get; set; }
        public Nullable<int> TourAllotment_CurType { get; set; }
        public Nullable<int> TourSchedule_ID { get; set; }
        public string HotelClassId { get; set; }
        public Nullable<byte> TourAllotment_ChildType1_FM { get; set; }
        public Nullable<byte> TourAllotment_ChildType1_To { get; set; }
        public Nullable<double> TourAllotment_ChildType1_Gross { get; set; }
        public Nullable<double> TourAllotment_ChildType1_Net { get; set; }
        public Nullable<byte> TourAllotment_ChildType2_FM { get; set; }
        public Nullable<byte> TourAllotment_ChildType2_To { get; set; }
        public Nullable<double> TourAllotment_ChildType2_Gross { get; set; }
        public Nullable<double> TourAllotment_ChildType2_Net { get; set; }
        public Nullable<bool> TourAllotment_IsChildAvailable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourFlightAllotment> TourFlightAllotments { get; set; }
    }
}
