//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TourSchedule()
        {
            this.PrivateTourPricings = new HashSet<PrivateTourPricing>();
        }
    
        public int Tour_Schedule_ID { get; set; }
        public int Tour_ID { get; set; }
        public Nullable<System.DateTime> TourSchedule_BeginDate { get; set; }
        public Nullable<System.DateTime> TourSchedule_EndDate { get; set; }
        public Nullable<int> TourSchedule_Increment { get; set; }
        public Nullable<decimal> TourSchedule_Price { get; set; }
        public Nullable<decimal> TourSchedule_SingleSupplement { get; set; }
        public Nullable<decimal> TourSchedule_TriplePrice { get; set; }
        public string TourSchedule_DepartureTime { get; set; }
        public string TourSchedule_ReturnTime { get; set; }
        public Nullable<bool> TourSchedule_RunOnSun { get; set; }
        public Nullable<bool> TourSchedule_RunOnMon { get; set; }
        public Nullable<bool> TourSchedule_RunOnTue { get; set; }
        public Nullable<bool> TourSchedule_RunOnWed { get; set; }
        public Nullable<bool> TourSchedule_RunOnThu { get; set; }
        public Nullable<bool> TourSchedule_RunOnFri { get; set; }
        public Nullable<bool> TourSchedule_RunOnSat { get; set; }
        public Nullable<int> TourSchedule_AlertValue { get; set; }
        public Nullable<int> TourSchedule_DaysBefore { get; set; }
        public Nullable<int> TourSchedule_Total { get; set; }
        public short Advse_Book_ID { get; set; }
        public Nullable<decimal> TourSchedule_DeluxeHotelSupplement { get; set; }
        public Nullable<decimal> TourSchedule_DeluxeHotelSingleSupplement { get; set; }
        public Nullable<decimal> TourSchedule_MealSupplement { get; set; }
        public Nullable<double> TourSchedule_MarkUp { get; set; }
        public Nullable<int> TourSchedule_CurType { get; set; }
        public Nullable<decimal> TourSchedule_PriceNet { get; set; }
        public Nullable<decimal> TourSchedule_SingleSupplementNet { get; set; }
        public Nullable<decimal> TourSchedule_TriplePriceNet { get; set; }
        public Nullable<decimal> TourSchedule_DeluxeHotelSupplementNet { get; set; }
        public Nullable<decimal> TourSchedule_DeluxeHotelSingleSupplementNet { get; set; }
        public string TourSchedule_Pick_up_Point { get; set; }
        public string TourSchedule_Time { get; set; }
        public string TourSchedule_Time_Drop_off { get; set; }
        public string TourSchedule_Point { get; set; }
        public string TourSchedule_Duration_Of_Tour { get; set; }
        public Nullable<bool> TourSchedule_PriceNet2 { get; set; }
        public Nullable<decimal> TicketCatAPrice { get; set; }
        public Nullable<decimal> TicketCatBPrice { get; set; }
        public Nullable<decimal> TicketCatAChildPrice { get; set; }
        public Nullable<decimal> TicketCatBChildPrice { get; set; }
        public string HotelClassId { get; set; }
        public Nullable<int> ChildType1_FM { get; set; }
        public Nullable<int> ChildType1_To { get; set; }
        public Nullable<double> ChildType1_Gross { get; set; }
        public Nullable<double> ChildType1_Net { get; set; }
        public Nullable<int> ChildType2_FM { get; set; }
        public Nullable<int> ChildType2_To { get; set; }
        public Nullable<double> ChildType2_Gross { get; set; }
        public Nullable<double> ChildType2_Net { get; set; }
        public Nullable<bool> IsChildAvailable { get; set; }
        public Nullable<bool> isExtended { get; set; }
        public Nullable<System.DateTime> ExtendDate { get; set; }
        public Nullable<int> ExtendedByAgent { get; set; }
        public Nullable<bool> isUpdated { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedByAgent { get; set; }
        public Nullable<byte> PrivateMode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrivateTourPricing> PrivateTourPricings { get; set; }
    }
}
