//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourServiceListDate
    {
        public Nullable<int> Tour_id { get; set; }
        public Nullable<int> Supl_id { get; set; }
        public Nullable<int> Tour_service_list_id { get; set; }
        public Nullable<int> TourServicelist_Day { get; set; }
        public Nullable<int> DefaultSupl_id { get; set; }
        public Nullable<int> Room_Id { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> AutoID { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public int KeyID { get; set; }
        public string HotelAdress { get; set; }
        public string HotelPhone { get; set; }
    }
}
