//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourCruiseSchedule
    {
        public int TourCruiseSchedule_ID { get; set; }
        public int Tour_ID { get; set; }
        public int Tour_Schedule_ID { get; set; }
        public int CruiseLine_ID { get; set; }
        public System.DateTime TourCruiseSchedule_BeginDate { get; set; }
        public System.DateTime TourCruiseSchedule_EndDate { get; set; }
        public Nullable<int> TourCruiseSchedule_AlertValue { get; set; }
        public Nullable<int> TourCruiseSchedule_DaysBefore { get; set; }
    }
}
