//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourServiceList_Supplier
    {
        public int Tour_ID { get; set; }
        public int Supl_ID { get; set; }
        public int Tour_Service_List_ID { get; set; }
        public int TourServiceList_Supplier_Day { get; set; }
        public Nullable<int> TourServiceList_Supplier_Nights { get; set; }
        public Nullable<int> TourServiceList_Supplier_DaysCharged { get; set; }
        public Nullable<int> TourServiceList_Supplier_ParentDay { get; set; }
        public Nullable<int> Tourdet_ID { get; set; }
        public Nullable<int> MainNotify { get; set; }
        public Nullable<int> DefaultList { get; set; }
        public Nullable<int> StartDestidCruise { get; set; }
        public Nullable<int> EndDestidCruise { get; set; }
        public Nullable<int> RoomID { get; set; }
        public int AutoID { get; set; }
        public Nullable<bool> BookedHotel { get; set; }
        public Nullable<bool> Temphuseyincnt { get; set; }
        public Nullable<int> PackageDestID { get; set; }
        public Nullable<int> ProviderCode { get; set; }
        public bool DepartureByPlane { get; set; }
        public bool DepartureByTrain { get; set; }
        public string DepartureLocation { get; set; }
    }
}
