//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourServiceList_HotelsByDate
    {
        public int ID { get; set; }
        public int Tour_ID { get; set; }
        public System.DateTime TourAllotmentDate { get; set; }
        public int Tourdet_ID { get; set; }
        public int Tour_Service_List_ID { get; set; }
        public int TourService_Day { get; set; }
        public int TourService_Nights { get; set; }
        public int Supl_ID { get; set; }
        public int RoomID { get; set; }
        public bool isBooked { get; set; }
        public Nullable<int> ProviderCode { get; set; }
    }
}
