//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourServiceList_SupplierAlternatives
    {
        public int Tour_ID { get; set; }
        public short Supplier_Day { get; set; }
        public int Default_Supl_ID { get; set; }
        public int Alternative_Supl_ID { get; set; }
        public Nullable<short> Hotel_Class_ID { get; set; }
        public Nullable<bool> DefaultHotel { get; set; }
        public Nullable<int> DefaultRoomTypeID { get; set; }
        public int AutoId { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
