//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourServiceList
    {
        public int Tour_ID { get; set; }
        public int Tour_Service_List_ID { get; set; }
        public string TourServiceList_Name { get; set; }
        public Nullable<int> TourServiceList_Rank { get; set; }
        public Nullable<bool> TourServiceList_ChargeDeluxeSupplement { get; set; }
        public Nullable<bool> TourServiceList_DefaultHotelList { get; set; }
        public Nullable<bool> TourServiceList_DisplayNameOnWeb { get; set; }
    }
}
