//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourSupplierSuggestion
    {
        public int ID { get; set; }
        public int Tour_ID { get; set; }
        public int Supl_ID { get; set; }
        public Nullable<decimal> TourSupplierSuggestion_Price { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string ShortDesc { get; set; }
    }
}
