//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourCruiseAllotment
    {
        public int TourCruiseAllotment_ID { get; set; }
        public int CruiseLine_ID { get; set; }
        public Nullable<int> Tour_Allotment_ID { get; set; }
        public Nullable<int> Cabin_ID { get; set; }
        public Nullable<int> TourCruiseAllotment_Total { get; set; }
        public Nullable<int> TourCruiseAllotment_Booked { get; set; }
        public Nullable<int> TourCruiseAllotment_Canceled { get; set; }
        public Nullable<System.DateTime> TourCruiseAllotment_CancelReminderDate { get; set; }
        public string TourCruiseAllotment_AlertValue { get; set; }
        public Nullable<int> Tour_Schedule_ID { get; set; }
    }
}
