//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelInsurance
    {
        public int Travel_Insurance_ID { get; set; }
        public Nullable<decimal> TravelInsurance_LowPrice { get; set; }
        public Nullable<decimal> TravelInsurance_HighPrice { get; set; }
        public Nullable<decimal> TravelInsurance_Price { get; set; }
        public Nullable<decimal> TravelInsurance_Net_Premium { get; set; }
    }
}
