//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelerPayment
    {
        public int TravelerPaymentID { get; set; }
        public int Payment_ID { get; set; }
        public int Quote_Passenger_ID { get; set; }
        public decimal PaymentAmount { get; set; }
    }
}
