//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelDocument
    {
        public int Ref_ID { get; set; }
        public Nullable<System.DateTime> DateToSendDocs { get; set; }
        public Nullable<bool> SentOrNot { get; set; }
        public Nullable<System.DateTime> Shipping_Date { get; set; }
        public string Tracking_Number { get; set; }
    }
}
