//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelGateXmlLog
    {
        public int ID { get; set; }
        public int RefID { get; set; }
        public string RequestType { get; set; }
        public string RequestSent { get; set; }
        public string ResponseRecieved { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
