//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelGateMealCode
    {
        public int ID { get; set; }
        public string SupplierAccessCode { get; set; }
        public string SupplierMealID { get; set; }
        public string SupplierMealCode { get; set; }
        public string SupplierMealCategory { get; set; }
        public string SupplierMealDescription { get; set; }
        public Nullable<int> MatchingID { get; set; }
    }
}
