//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRolesPage
    {
        public int UserRolePage { get; set; }
        public Nullable<int> UserRole { get; set; }
        public string PagesName { get; set; }
        public string PageDesc { get; set; }
        public Nullable<int> visible { get; set; }
        public Nullable<int> PageNo { get; set; }
        public Nullable<int> Select { get; set; }
    }
}
