//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string User_Login { get; set; }
        public string User_Password { get; set; }
        public int UserProfile_ID { get; set; }
        public int User_ExternalID { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public Nullable<System.DateTime> User_Created { get; set; }
        public int UserID { get; set; }
        public bool isActivated { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
