//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivation
    {
        public int UserActivationID { get; set; }
        public System.Guid UserActivationKey { get; set; }
        public int UserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool isUsed { get; set; }
    }
}
