//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRolesPages_filter_Types
    {
        public int FilterID { get; set; }
        public Nullable<int> PageNr { get; set; }
        public string PageName { get; set; }
        public string filterDisplayName { get; set; }
        public string filternames { get; set; }
        public Nullable<int> filterOrder { get; set; }
        public string filterType { get; set; }
    }
}
