//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class W2M_ZoneList
    {
        public int Code { get; set; }
        public string JPDCode { get; set; }
        public string Name { get; set; }
        public Nullable<int> Parent { get; set; }
        public string IATA { get; set; }
        public string Type { get; set; }
        public string ClientType { get; set; }
        public bool Hotels { get; set; }
        public bool Searchable { get; set; }
        public bool isDeleted { get; set; }
    }
}
