//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class W2M_Facilities
    {
        public int ID { get; set; }
        public int W2M_Id { get; set; }
        public int W2M_Code { get; set; }
        public string W2M_Category { get; set; }
        public string W2M_Facility { get; set; }
    }
}
