//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class W2M_ZonesWithParents
    {
        public int Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Parents { get; set; }
    }
}
