//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebUser
    {
        public int Web_User_ID { get; set; }
        public int Cust_ID { get; set; }
        public string WebUser_FirstName { get; set; }
        public string WebUser_LastName { get; set; }
        public string WebUser_UserName { get; set; }
        public string WebUser_Password { get; set; }
        public string WebUser_PhoneNumber { get; set; }
        public string WebUser_Extention { get; set; }
        public string WebUser_Email { get; set; }
        public Nullable<bool> WebUser_AdressSameAsCustomer { get; set; }
        public string WebUser_Address1 { get; set; }
        public string WebUser_Address2 { get; set; }
        public string WebUser_City { get; set; }
        public string WebUser_State { get; set; }
        public string WebUser_ZipCode { get; set; }
        public string WebUser_Country { get; set; }
        public byte[] WebUser_DateCreated { get; set; }
        public string WebUser_ShippingAddress1 { get; set; }
        public string WebUser_ShippingAddress2 { get; set; }
        public string WebUser_ShippingCity { get; set; }
        public string WebUser_ShippingState { get; set; }
        public string WebUser_ShippingZipCode { get; set; }
        public string WebUser_UserType { get; set; }
        public string WebUser_DepartureGateway { get; set; }
        public Nullable<bool> WebUser_ShippingSameAsMailing { get; set; }
        public Nullable<int> WebUser_CurrentQuote { get; set; }
        public Nullable<bool> WebUser_SendNewsLetters { get; set; }
        public Nullable<bool> WebUser_SendBrochures { get; set; }
        public string WebUser_RegisterType { get; set; }
        public Nullable<int> Referrer_ID { get; set; }
        public string WebUser_Province { get; set; }
        public string WebUser_ShippingProvince { get; set; }
        public string WebUser_ShippingCountry { get; set; }
        public Nullable<int> UserProfile_ID { get; set; }
        public Nullable<System.DateTime> WebUser_Created { get; set; }
        public Nullable<int> Old_Cust_ID { get; set; }
        public Nullable<int> UpdateInfo { get; set; }
        public Nullable<int> new_Cust_ID { get; set; }
        public bool DoNotMail { get; set; }
        public bool isDeleted { get; set; }
        public decimal PointEarned { get; set; }
        public decimal PointPending { get; set; }
        public string FacebookID { get; set; }
        public string GoogleID { get; set; }
        public bool isActivated { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public bool isMigrated { get; set; }
    
        public virtual Custom Custom { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
