//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishListItem
    {
        public int WishListItemId { get; set; }
        public int WishListId { get; set; }
        public int ServiceTypeId { get; set; }
        public Nullable<int> Tour_ID { get; set; }
        public Nullable<int> ParcesHotelId { get; set; }
        public Nullable<int> Supl_ID { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public Nullable<int> ProviderCode { get; set; }
        public string ServiceName { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> CruiseRegionID { get; set; }
        public Nullable<int> CruiseID { get; set; }
        public Nullable<int> VoyageID { get; set; }
        public Nullable<int> TourTypeID { get; set; }
        public string TourCode { get; set; }
        public string ProviderID { get; set; }
    }
}
