//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class xmlGeneratorRule
    {
        public int XmlCompId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string StartCity { get; set; }
        public string StartCountry { get; set; }
        public string TourName { get; set; }
        public string LandOption { get; set; }
        public string TourCodes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CompanyName { get; set; }
        public Nullable<bool> isNewXml { get; set; }
    }
}
