//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class XMLItem
    {
        public int ID { get; set; }
        public int ItemRefID { get; set; }
        public short ItemNumber { get; set; }
        public int ProviderCode { get; set; }
    }
}
